import type { SeedArtifact } from './types';
/**
 * The 23 Section-14 anchor artifacts from the build prompt — real, dated, dissertation-bearing.
 * Axis values and reasoning are transcribed from the spec (the author's draft analysis); they load
 * as proposals and are refined in the vetting queue. URLs and dates are the spec's canonical ones.
 */
export const ANCHORS: SeedArtifact[] = [
  {
    externalId: 'anchor-01-family-of-man',
    title: 'The Family of Man (Edward Steichen, MoMA, 1955)',
    description:
      'USIA-sponsored MoMA photography exhibition, curated by Steichen; toured 37 nations to ~9M viewers. The 20th-century cultural-diplomacy artifact the work descends from and updates.',
    url: 'https://www.moma.org/calendar/exhibitions/2429',
    mediaType: 'mixed',
    publishedAt: '1955-01-24',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'state_affiliated',
    era: '1998–2005',
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Clearly identifiable single curatorial origin: USIA-sponsored MoMA exhibition, Steichen as curator.' },
      { axis: 'reach', value: 0.95, reasoning: 'Toured 37 nations, ~9M viewers — the largest cultural-diplomacy artifact of the 20th century.' },
      { axis: 'aesthetic_signal', value: 0.8, reasoning: 'Distinctive humanist photographic grammar, identifiable from a single image.' },
      { axis: 'diplomatic_cross_boundary', value: 0.9, reasoning: 'State-sponsored cross-border circulation by design.' },
      { axis: 'diplomatic_authenticity', value: 0.45, reasoning: 'Its universalism flattened cultural specificity; Barthes’ Mythologies critique applies.' },
      { axis: 'diplomatic_reciprocity', value: 0.3, reasoning: 'A broadcasting model, not exchange; reciprocity assumed rather than achieved.' },
    ],
  },
  {
    externalId: 'anchor-02-bamboozled',
    title: 'Bamboozled (Spike Lee, 2000)',
    description:
      'Spike Lee’s DV-shot satire of minstrelsy in American media; a touchstone of the indie digital-video era Manovich called “DV realism.”',
    url: 'https://en.wikipedia.org/wiki/Bamboozled',
    mediaType: 'video',
    publishedAt: '2000-10-06',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: '1998–2005',
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Unambiguously American, Spike Lee’s authorial fingerprint.' },
      { axis: 'reach', value: 0.4, reasoning: 'Limited theatrical release, modest international distribution.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'Sony VX-1000 DV grammar, deliberately rough.' },
      { axis: 'diplomatic_cross_boundary', value: 0.25, reasoning: 'Largely a domestic American conversation.' },
      { axis: 'diplomatic_authenticity', value: 0.95, reasoning: 'Carries its origin’s racial-political specificity uncompromised.' },
      { axis: 'diplomatic_reciprocity', value: 0.2, reasoning: 'One-way, US-domestic.' },
    ],
  },
  {
    externalId: 'anchor-03-walmart-high-cost',
    title: 'Wal-Mart: The High Cost of Low Price (Robert Greenwald, 2005)',
    description:
      'Advocacy documentary distributed through 7,000+ community screenings via internet and DVD rather than theaters — the production-democratization argument made concrete.',
    url: 'https://en.wikipedia.org/wiki/Wal-Mart:_The_High_Cost_of_Low_Price',
    mediaType: 'video',
    publishedAt: '2005-11-04',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: '1998–2005',
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'American documentary tradition, Greenwald’s authorial voice.' },
      { axis: 'reach', value: 0.5, reasoning: '7,000+ community screenings via internet and DVD; deliberately non-theatrical.' },
      { axis: 'aesthetic_signal', value: 0.45, reasoning: 'Advocacy-documentary template grammar.' },
      { axis: 'diplomatic_cross_boundary', value: 0.2, reasoning: 'Domestic American advocacy.' },
      { axis: 'diplomatic_authenticity', value: 0.85, reasoning: 'Origin specificity intact and intentional.' },
      { axis: 'diplomatic_reciprocity', value: 0.15, reasoning: 'One-directional distribution model.' },
    ],
  },
  {
    externalId: 'anchor-04-dv-made-china',
    title: 'DV-Made China: grassroots digital filmmaking (c. 2002–2008)',
    description:
      'Chinese provincial DV-vérité filmmaking communities (Zhang Zhen & Zito, eds.). A counter-example: democratization without diplomatic travel.',
    url: 'https://uhpress.hawaii.edu/title/dv-made-china/',
    mediaType: 'mixed',
    publishedAt: '2005-01-01',
    originCountryCodes: ['CN'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: '1998–2005',
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Chinese provincial filmmaking communities, identifiable through the volume’s case studies.' },
      { axis: 'reach', value: 0.2, reasoning: 'Largely circulated within China; limited Western academic circulation.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'Distinctive grammar of the DV-vérité movement in the PRC context.' },
      { axis: 'diplomatic_cross_boundary', value: 0.1, reasoning: 'Stayed within its national context.' },
      { axis: 'diplomatic_authenticity', value: 0.95, reasoning: 'Origin specificity is the whole point.' },
      { axis: 'diplomatic_reciprocity', value: 0.1, reasoning: 'No reciprocal exchange.' },
    ],
  },
  {
    externalId: 'anchor-05-me-at-the-zoo',
    title: '“Me at the zoo” (Jawed Karim, first YouTube video, 2005)',
    description:
      'The first YouTube upload; the historical opening of the platform-mediated era of cultural production.',
    url: 'https://www.youtube.com/watch?v=jNQXAC9IVRw',
    mediaType: 'video',
    publishedAt: '2005-04-23',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: '2005–2012',
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'San Diego Zoo, American teenager, identifiable to the second.' },
      { axis: 'reach', value: 0.9, reasoning: '350M+ views; the opening of the YouTube era.' },
      { axis: 'aesthetic_signal', value: 0.3, reasoning: 'Deliberately unremarkable — the vernacular at zero.' },
      { axis: 'diplomatic_cross_boundary', value: 0.55, reasoning: 'Viewed globally as a historical artifact rather than an American export.' },
      { axis: 'diplomatic_authenticity', value: 0.85, reasoning: 'Carries its origin specificity precisely because of its banality.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Multiple-language commentary continues two decades later.' },
    ],
  },
  {
    externalId: 'anchor-06-gangnam-style',
    title: 'Gangnam Style (Psy, 2012)',
    description:
      'First video to cross 1B views; Seoul-specific satire that traveled globally — early evidence that platform-mediated cultural travel could be substantial.',
    url: 'https://www.youtube.com/watch?v=9bZkp7q19f0',
    mediaType: 'video',
    publishedAt: '2012-07-15',
    originCountryCodes: ['KR'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: '2005–2012',
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Seoul-specific satirical commentary; the song’s cultural specificity matters.' },
      { axis: 'reach', value: 0.98, reasoning: 'First video past 1B views; over 5B; charted in 30+ countries.' },
      { axis: 'aesthetic_signal', value: 0.9, reasoning: 'Instantly recognizable K-pop production grammar.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'Genuine cross-cultural travel, including Western engagement with Korean context.' },
      { axis: 'diplomatic_authenticity', value: 0.65, reasoning: 'The Gangnam-as-elite satire was widely flattened in international reception.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Parodies and covers generated globally; some flowed back to Korea.' },
    ],
  },
  {
    externalId: 'anchor-07-arab-spring',
    title: 'Arab Spring social-media artifacts (2010–2012)',
    description:
      'Smartphone-shot protest documentation across Tunisia, Egypt, Libya, Syria — the cyber-optimist/skeptic debate the work inherits (Howard et al. 2011).',
    url: 'https://www.washington.edu/news/2011/09/12/new-study-quantifies-use-of-social-media-in-arab-spring/',
    mediaType: 'mixed',
    publishedAt: '2011-01-25',
    originCountryCodes: ['EG', 'TN'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: '2005–2012',
    scores: [
      { axis: 'origin', value: 0.65, reasoning: 'Multiple national contexts; identifiable per artifact.' },
      { axis: 'reach', value: 0.85, reasoning: 'Global circulation and sustained news amplification.' },
      { axis: 'aesthetic_signal', value: 0.5, reasoning: 'Vernacular smartphone urgency — the poor image Steyerl theorized.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'Crossed borders into global publics rapidly.' },
      { axis: 'diplomatic_authenticity', value: 0.85, reasoning: 'Civilian provenance carries strong origin specificity.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Western reception largely framed events through Western categories (Wolfsfeld 2013).' },
    ],
  },
  {
    externalId: 'anchor-08-youtube-watch-time',
    title: 'YouTube’s watch-time pivot (2012)',
    description:
      'YouTube’s announcement of optimizing for watch time — the propagation-infrastructure decision that set what travels for the next decade.',
    url: 'https://blog.youtube/news-and-events/youtube-now-why-we-focus-on-watch-time/',
    mediaType: 'text',
    publishedAt: '2012-03-01',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: '2012–2018',
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'A Google/YouTube engineering decision, San Bruno.' },
      { axis: 'reach', value: 0.95, reasoning: 'Reshaped the global content economy.' },
      { axis: 'aesthetic_signal', value: 0.2, reasoning: 'A technical change with no aesthetic fingerprint of its own.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'Effectively created the cross-border algorithmic content economy.' },
      { axis: 'diplomatic_authenticity', value: 0.15, reasoning: 'Watch-time optimization flattens cultural specificity for retention.' },
      { axis: 'diplomatic_reciprocity', value: 0.1, reasoning: 'The architecture disincentivizes reciprocity.' },
    ],
  },
  {
    externalId: 'anchor-09-bts-spring-day',
    title: 'BTS, “Spring Day” (2017)',
    description:
      'The mature K-pop aesthetic of the 2010s Korean Wave; the strongest contemporary case of platform-affordance cultural diplomacy (Jin 2024).',
    url: 'https://www.youtube.com/watch?v=xEeFrLSkMm8',
    mediaType: 'video',
    publishedAt: '2017-02-13',
    originCountryCodes: ['KR'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: '2012–2018',
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'BigHit production, Korean cultural context referenced explicitly.' },
      { axis: 'reach', value: 0.95, reasoning: 'Global chart and streaming reach.' },
      { axis: 'aesthetic_signal', value: 0.95, reasoning: 'The defining K-pop aesthetic of the decade.' },
      { axis: 'diplomatic_cross_boundary', value: 0.9, reasoning: 'Substantial cross-cultural travel into Western audiences.' },
      { axis: 'diplomatic_authenticity', value: 0.8, reasoning: 'Preserved more cultural specificity than industry-typical export-optimization.' },
      { axis: 'diplomatic_reciprocity', value: 0.7, reasoning: 'Western ARMY fandoms generated content that flowed back to Korea — a rare high-reciprocity case.' },
    ],
  },
  {
    externalId: 'anchor-10-syria-smartphone',
    title: 'Smartphone-shot conflict documentation, Syria (2012–2016)',
    description:
      'Civilian and witness footage geolocatable by Forensic Architecture methods — smartphone ubiquity producing a documentation regime no prior conflict had.',
    url: 'https://www.amnesty.org/en/latest/news/2016/05/syria-the-human-slaughterhouse/',
    mediaType: 'video',
    publishedAt: '2014-01-01',
    originCountryCodes: ['SY'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: '2012–2018',
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Syrian civilian provenance, geolocatable per Forensic Architecture methodology.' },
      { axis: 'reach', value: 0.7, reasoning: 'Significant global circulation through rights organizations and press.' },
      { axis: 'aesthetic_signal', value: 0.65, reasoning: 'The poor image functioning as evidence rather than style.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'Crossed into global humanitarian discourse.' },
      { axis: 'diplomatic_authenticity', value: 0.9, reasoning: 'Origin specificity is the evidentiary point.' },
      { axis: 'diplomatic_reciprocity', value: 0.25, reasoning: 'Largely one-directional witness-to-world flow.' },
    ],
  },
  {
    externalId: 'anchor-11-tiktok-fyp',
    title: 'TikTok For You Page launch (2018)',
    description:
      'ByteDance’s recommendation feed — a cross-cultural delivery mechanism by design; the present-day infrastructure of content travel.',
    url: 'https://newsroom.tiktok.com/en-us/how-tiktok-recommends-videos-for-you',
    mediaType: 'text',
    publishedAt: '2018-08-01',
    originCountryCodes: ['CN'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: '2018–2024',
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'ByteDance, Beijing.' },
      { axis: 'reach', value: 0.95, reasoning: 'Global reach across the content economy.' },
      { axis: 'aesthetic_signal', value: 0.3, reasoning: 'An infrastructure decision without an aesthetic of its own.' },
      { axis: 'diplomatic_cross_boundary', value: 0.95, reasoning: 'The For You Page is a cross-cultural delivery mechanism by design.' },
      { axis: 'diplomatic_authenticity', value: 0.3, reasoning: 'The loneliness effect and algorithmic localization narrow cultural exposure.' },
      { axis: 'diplomatic_reciprocity', value: 0.2, reasoning: 'Architecture disincentivizes reciprocity.' },
    ],
  },
  {
    externalId: 'anchor-12-nollywood-netflix',
    title: 'Nollywood transnational distribution (Netflix era, 2021–2024)',
    description:
      'Lagos-based production traveling Global-South-to-North via Netflix — counter-evidence to the typical reach asymmetry.',
    url: 'https://www.netflix.com/title/81226204',
    mediaType: 'video',
    publishedAt: '2021-08-27',
    originCountryCodes: ['NG'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: '2018–2024',
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Lagos-based production, identifiable narrative grammar.' },
      { axis: 'reach', value: 0.7, reasoning: 'Netflix global distribution; significant African-diaspora engagement.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'Distinctive Nollywood production grammar.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'Global-South-to-North travel.' },
      { axis: 'diplomatic_authenticity', value: 0.7, reasoning: 'Netflix-era production-value smoothing flattens some specificity.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'Partial reciprocity through diaspora circulation.' },
    ],
  },
  {
    externalId: 'anchor-13-zelenskyy-2022',
    title: 'Zelenskyy wartime addresses (first 100 days, 2022)',
    description:
      'The green-t-shirt evening-address grammar; the contemporary state-led public-diplomacy case study.',
    url: 'https://www.president.gov.ua/en',
    mediaType: 'video',
    publishedAt: '2022-02-25',
    originCountryCodes: ['UA'],
    aiMediation: 'human_made',
    authorshipClass: 'state_affiliated',
    era: '2018–2024',
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Unambiguous Ukrainian state origin.' },
      { axis: 'reach', value: 0.95, reasoning: 'Real-time global reach and amplification.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'The green-t-shirt grammar became iconic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.95, reasoning: 'Real-time global cross-cultural engagement.' },
      { axis: 'diplomatic_authenticity', value: 0.85, reasoning: 'Origin specificity preserved through subtitle infrastructure.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Global support visibly flowed back into Ukrainian domestic discourse.' },
    ],
  },
  {
    externalId: 'anchor-14-youtube-ai-dubbing',
    title: 'YouTube AI multi-language dubbing (Aloud, 2023 onward)',
    description:
      'AI-dubbing applied to cross-cultural content — the post-2023 inflection in cross-cultural reach, with a mixed effect on cultural translation.',
    url: 'https://blog.youtube/news-and-events/aloud-multi-language-audio-now-available/',
    mediaType: 'video',
    publishedAt: '2023-11-01',
    originCountryCodes: ['KR'],
    aiMediation: 'ai_assisted',
    authorshipClass: 'commercial_institutional',
    era: '2018–2024',
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Identifiable source content with an AI-mediation layer added.' },
      { axis: 'reach', value: 0.95, reasoning: 'AI-dubbing widens audience reach substantially.' },
      { axis: 'aesthetic_signal', value: 0.8, reasoning: 'Source aesthetic preserved; voice timbre retained.' },
      { axis: 'diplomatic_cross_boundary', value: 0.95, reasoning: 'Removes the language barrier to cross-cultural travel.' },
      { axis: 'diplomatic_authenticity', value: 0.55, reasoning: 'Preserves timbre but loses subtitling’s reading-as-translation; mixed.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Reach is widened but exchange remains largely one-way.' },
    ],
  },
  {
    externalId: 'anchor-15-dcweekly-ai-propaganda',
    title: 'DCWeekly.org AI-generated propaganda (2023–2025)',
    description:
      'Russian-affiliated influence operation presenting AI-generated content as American local news — the negative case: volume without persuasion (Wack et al. 2025).',
    url: 'https://academic.oup.com/pnasnexus/article/4/4/pgaf083/8095340',
    mediaType: 'text',
    publishedAt: '2025-04-01',
    originCountryCodes: ['RU'],
    aiMediation: 'ai_generated',
    authorshipClass: 'ambiguous_unattributable',
    era: '2024–2026',
    scores: [
      { axis: 'origin', value: 0.3, reasoning: 'Deliberately obscured; Russian-affiliated, presented as American local news.' },
      { axis: 'reach', value: 0.4, reasoning: 'High throughput; modest individual-artifact reach.' },
      { axis: 'aesthetic_signal', value: 0.2, reasoning: 'Template news-text aesthetic, no distinctive signature.' },
      { axis: 'diplomatic_cross_boundary', value: 0.65, reasoning: 'Crosses borders by disguise rather than by travel.' },
      { axis: 'diplomatic_authenticity', value: 0.1, reasoning: 'Origin actively suppressed — the inverse of authentic travel.' },
      { axis: 'diplomatic_reciprocity', value: 0.05, reasoning: 'No exchange; pure projection.' },
    ],
  },
  {
    externalId: 'anchor-16-kling-cinematic',
    title: 'Chinese generative-AI cinematic content (Kling, 2024–2025)',
    description:
      'Kuaishou’s Kling video model and its outputs — the cinematic-sovereignty argument made concrete; a Chinese model with Hollywood-trained narrative grammar.',
    url: 'https://kling.kuaishou.com/',
    mediaType: 'video',
    publishedAt: '2025-01-01',
    originCountryCodes: ['CN'],
    aiMediation: 'ai_generated',
    authorshipClass: 'commercial_institutional',
    era: '2024–2026',
    scores: [
      { axis: 'origin', value: 0.5, reasoning: 'Chinese model, but Hollywood-trained narrative grammar; layered provenance.' },
      { axis: 'reach', value: 0.7, reasoning: 'Wide adoption among creators.' },
      { axis: 'aesthetic_signal', value: 0.65, reasoning: 'Recognizable model fingerprints across outputs.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'Outputs circulate across borders readily.' },
      { axis: 'diplomatic_authenticity', value: 0.3, reasoning: 'Model defaults flatten cultural specificity by design.' },
      { axis: 'diplomatic_reciprocity', value: 0.15, reasoning: 'One-way generation, little reciprocal exchange.' },
    ],
  },
  {
    externalId: 'anchor-17-runway-gen4',
    title: 'Western generative-AI cinematic content (Runway Gen-4, 2025)',
    description:
      'Runway’s Gen-4 video model — the Western counterpart for the cinematic-sovereignty comparison.',
    url: 'https://runwayml.com/research/introducing-runway-gen-4',
    mediaType: 'video',
    publishedAt: '2025-03-31',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'commercial_institutional',
    era: '2024–2026',
    scores: [
      { axis: 'origin', value: 0.5, reasoning: 'Western model with broadly trained, layered provenance.' },
      { axis: 'reach', value: 0.65, reasoning: 'Significant creator adoption.' },
      { axis: 'aesthetic_signal', value: 0.65, reasoning: 'Recognizable model fingerprints.' },
      { axis: 'diplomatic_cross_boundary', value: 0.65, reasoning: 'Outputs travel across borders.' },
      { axis: 'diplomatic_authenticity', value: 0.3, reasoning: 'Defaults flatten cultural specificity.' },
      { axis: 'diplomatic_reciprocity', value: 0.2, reasoning: 'Largely one-directional generation.' },
    ],
  },
  {
    externalId: 'anchor-18-yoasobi-idol',
    title: 'YOASOBI, “Idol” / anime cross-cultural reach (2023)',
    description:
      'The Oshi no Ko opening; the strongest contemporary case for high-authenticity, high-reach cultural travel — Cool Japan as the Korean Wave’s analog.',
    url: 'https://www.youtube.com/watch?v=ZRtdQ81jPUQ',
    mediaType: 'video',
    publishedAt: '2023-04-12',
    originCountryCodes: ['JP'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: '2018–2024',
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Unambiguously Japanese production and cultural context.' },
      { axis: 'reach', value: 0.95, reasoning: '600M+ views; global chart presence.' },
      { axis: 'aesthetic_signal', value: 0.95, reasoning: 'Distinctive J-pop/anime production grammar.' },
      { axis: 'diplomatic_cross_boundary', value: 0.95, reasoning: 'Strong cross-cultural travel without losing its register.' },
      { axis: 'diplomatic_authenticity', value: 0.85, reasoning: 'High cultural specificity preserved in global reception.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Global fan covers and responses flow back to Japan.' },
    ],
  },
  {
    externalId: 'anchor-19-chronicle-old-knight',
    title: 'Chronicle Studios AI-optimized distribution, “The Old Knight” (2025)',
    description:
      'AI audience-routing claiming a 13x impressions lift — the propagation-infrastructure layer the dissertation most needs to study.',
    url: 'https://www.businesswire.com/news/home/20251210/',
    mediaType: 'video',
    publishedAt: '2025-12-10',
    originCountryCodes: ['US'],
    aiMediation: 'ai_assisted',
    authorshipClass: 'commercial_institutional',
    era: '2024–2026',
    scores: [
      { axis: 'origin', value: 0.5, reasoning: 'Identifiable studio, but AI-routing obscures the path to audiences.' },
      { axis: 'reach', value: 0.8, reasoning: 'A documented 13x impressions claim.' },
      { axis: 'aesthetic_signal', value: 0.55, reasoning: 'Conventional production with an optimization layer.' },
      { axis: 'diplomatic_cross_boundary', value: 0.65, reasoning: 'AI routing carries it across audiences and borders.' },
      { axis: 'diplomatic_authenticity', value: 0.2, reasoning: 'Audience-routing optimizes for engagement, not cultural specificity.' },
      { axis: 'diplomatic_reciprocity', value: 0.1, reasoning: 'One-directional distribution optimization.' },
    ],
  },
  {
    externalId: 'anchor-20-paris-2024-ceremony',
    title: 'Paris 2024 Olympics Opening Ceremony',
    description:
      'State-coordinated cultural diplomacy at its largest contemporary scale; French specificity foregrounded but internationally legible.',
    url: 'https://www.youtube.com/watch?v=BHO1B4kE-pE',
    mediaType: 'video',
    publishedAt: '2024-07-26',
    originCountryCodes: ['FR'],
    aiMediation: 'human_made',
    authorshipClass: 'state_affiliated',
    era: '2024–2026',
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Unambiguous French state-coordinated authorship.' },
      { axis: 'reach', value: 0.95, reasoning: 'One of the largest live global audiences.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'Distinctive, heavily art-directed staging.' },
      { axis: 'diplomatic_cross_boundary', value: 0.95, reasoning: 'Designed for a global cross-cultural audience.' },
      { axis: 'diplomatic_authenticity', value: 0.7, reasoning: 'French specificity foregrounded but explicitly internationally legible.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Global participation and response are part of the form.' },
    ],
  },
  {
    externalId: 'anchor-21-calculating-empires',
    title: 'Calculating Empires (Kate Crawford & Vladan Joler, 2023)',
    description:
      'A large-scale visual genealogy of technology and power (Venice Biennale 2025 Silver Lion) — the structural precedent Origin Unknown descends from.',
    url: 'https://calculatingempires.net/',
    mediaType: 'mixed',
    publishedAt: '2023-11-01',
    originCountryCodes: ['US', 'RS'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: '2024–2026',
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Jointly authored; a clearly identifiable critical-AI-systems lineage.' },
      { axis: 'reach', value: 0.6, reasoning: 'Museum and academic circulation rather than popular.' },
      { axis: 'aesthetic_signal', value: 0.95, reasoning: 'A visual-database grammar; the structural precedent for this project.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'Exhibited across Milan, Tokyo, Paris, Barcelona, Berlin.' },
      { axis: 'diplomatic_authenticity', value: 0.95, reasoning: 'Deeply specific, rigorously authored.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Scholarly dialogue and citation flow in both directions.' },
    ],
  },
  {
    externalId: 'anchor-22-dunhuang-digital-cave',
    title: 'Dunhuang Academy “Digital Library Cave” (2022 onward)',
    description:
      'State-coordinated AI-mediated reconstruction of Mogao-Grottoes heritage through a scholarly partnership network — the most substantive contemporary state AI cultural-diplomacy case.',
    url: 'https://www.e-dunhuang.com/',
    mediaType: 'mixed',
    publishedAt: '2022-01-01',
    originCountryCodes: ['CN'],
    aiMediation: 'ai_assisted',
    authorshipClass: 'state_affiliated',
    era: '2018–2024',
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Dunhuang Academy of China, state-coordinated.' },
      { axis: 'reach', value: 0.45, reasoning: 'Scholarly and heritage-audience reach.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'Distinctive Mogao Buddhist-heritage aesthetic, AI-mediated reconstruction.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'Travels through an international partnership network.' },
      { axis: 'diplomatic_authenticity', value: 0.85, reasoning: 'Origin specificity preserved through scholarly partnership.' },
      { axis: 'diplomatic_reciprocity', value: 0.65, reasoning: 'Genuine multi-institutional bilateral collaboration.' },
    ],
  },
  {
    externalId: 'anchor-23-lelapa-ai',
    title: 'Lelapa AI negotiated data-funding model (2024–2025)',
    description:
      'A Johannesburg AI company’s negotiated, bilateral data relationships — the counter-example to data colonialism the reciprocity sub-measure exists to register.',
    url: 'https://lelapa.ai/',
    mediaType: 'text',
    publishedAt: '2024-06-01',
    originCountryCodes: ['ZA'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: '2024–2026',
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Johannesburg-based, identifiable founder team.' },
      { axis: 'reach', value: 0.25, reasoning: 'Industry and policy circulation rather than mass reach.' },
      { axis: 'aesthetic_signal', value: 0.5, reasoning: 'A model/text artifact rather than a crafted media object.' },
      { axis: 'diplomatic_cross_boundary', value: 0.55, reasoning: 'Engages North-South data relationships directly.' },
      { axis: 'diplomatic_authenticity', value: 0.95, reasoning: 'Grounded, specific, community-accountable.' },
      { axis: 'diplomatic_reciprocity', value: 0.9, reasoning: 'Negotiated bilateral data relationships rather than extraction — the rare high-reciprocity case.' },
    ],
  },
];
