import type { SeedArtifact } from './types';
/**
 * Era 2005–2012 — the YouTube era: platform-mediated virality, the first creator economy, and the
 * early Korean/Indian web breakouts. Draft scores in the v1.2 construct (origin: high = clear).
 */
const ERA = '2005–2012';
export const ERA_2005_2012: SeedArtifact[] = [
  {
    externalId: 'e2-evolution-of-dance',
    title: 'Evolution of Dance (Judson Laipply, 2006)',
    description: 'A six-minute dance medley that became one of YouTube’s first mega-viral videos and most-viewed clip of the early platform.',
    url: 'https://en.wikipedia.org/wiki/Evolution_of_Dance',
    mediaType: 'video',
    publishedAt: '2006-04-06',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear single performer/author.' },
      { axis: 'reach', value: 0.8, reasoning: 'The most-viewed YouTube video for years.' },
      { axis: 'aesthetic_signal', value: 0.5, reasoning: 'A one-take stage performance, charm over production.' },
      { axis: 'diplomatic_cross_boundary', value: 0.5, reasoning: 'A medley of mostly American pop-culture references.' },
      { axis: 'diplomatic_authenticity', value: 0.5, reasoning: 'Authentic but culturally light.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Sparked imitation dance videos.' },
    ],
  },
  {
    externalId: 'e2-lonelygirl15',
    title: 'lonelygirl15 (2006)',
    description: 'A YouTube video diary presented as a real teenager that was secretly scripted fiction — a foundational case of deliberately ambiguous origin.',
    url: 'https://en.wikipedia.org/wiki/Lonelygirl15',
    mediaType: 'video',
    publishedAt: '2006-06-16',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.3, reasoning: 'Origin deliberately disguised: scripted fiction posing as authentic vlog.' },
      { axis: 'reach', value: 0.65, reasoning: 'A landmark early-YouTube phenomenon.' },
      { axis: 'aesthetic_signal', value: 0.55, reasoning: 'Defined the confessional vlog aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.4, reasoning: 'Largely an Anglophone audience.' },
      { axis: 'diplomatic_authenticity', value: 0.2, reasoning: 'Its appeal rested on a false claim of authenticity.' },
      { axis: 'diplomatic_reciprocity', value: 0.35, reasoning: 'Audience speculation fed the narrative.' },
    ],
  },
  {
    externalId: 'e2-rickroll',
    youtubeId: 'dQw4w9WgXcQ',
    title: 'Rickroll — “Never Gonna Give You Up” (2007)',
    description: 'A bait-and-switch link prank built on Rick Astley’s 1987 song — perhaps the most enduring participatory meme of the web.',
    url: 'https://en.wikipedia.org/wiki/Rickrolling',
    mediaType: 'video',
    publishedAt: '2007-05-15',
    originCountryCodes: ['GB'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.6, reasoning: 'A clear song source, but the prank is collectively authored.' },
      { axis: 'reach', value: 0.85, reasoning: 'A globally understood internet ritual for over 15 years.' },
      { axis: 'aesthetic_signal', value: 0.5, reasoning: 'The aesthetic is the gag, not the video.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'Practiced across the world’s internet cultures.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'A pure in-joke, not cultural expression.' },
      { axis: 'diplomatic_reciprocity', value: 0.65, reasoning: 'Endlessly re-performed by everyone — deeply participatory.' },
    ],
  },
  {
    externalId: 'e2-charlie-bit-my-finger',
    title: 'Charlie Bit My Finger (2007)',
    description: 'A 56-second home clip that became one of the most-viewed YouTube videos — the apotheosis of incidental family virality.',
    url: 'https://en.wikipedia.org/wiki/Charlie_Bit_My_Finger',
    mediaType: 'video',
    publishedAt: '2007-05-22',
    originCountryCodes: ['GB'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'A known family, posted privately then globally embraced.' },
      { axis: 'reach', value: 0.85, reasoning: 'Among the most-viewed videos of its era.' },
      { axis: 'aesthetic_signal', value: 0.2, reasoning: 'Unstyled home video.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'A universally legible domestic moment.' },
      { axis: 'diplomatic_authenticity', value: 0.7, reasoning: 'Authentic precisely because it is ordinary.' },
      { axis: 'diplomatic_reciprocity', value: 0.3, reasoning: 'Mostly one-way viewing.' },
    ],
  },
  {
    externalId: 'e2-chocolate-rain',
    title: 'Chocolate Rain (Tay Zonday, 2007)',
    description: 'A homemade song whose distinctive voice and lyrics became a defining early-YouTube music meme.',
    url: 'https://en.wikipedia.org/wiki/Chocolate_Rain',
    mediaType: 'video',
    publishedAt: '2007-04-22',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear single creator.' },
      { axis: 'reach', value: 0.65, reasoning: 'A canonical early-YouTube hit.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'An unmistakable voice and home-studio look.' },
      { axis: 'diplomatic_cross_boundary', value: 0.4, reasoning: 'Mostly an Anglophone audience.' },
      { axis: 'diplomatic_authenticity', value: 0.65, reasoning: 'Earnest, self-authored social commentary.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'Widely covered and parodied.' },
    ],
  },
  {
    externalId: 'e2-i-can-has-cheezburger',
    title: 'I Can Has Cheezburger? / lolcats (2007)',
    description: 'The site that codified image-macro humor — a template that shaped the grammar of internet memes.',
    url: 'https://en.wikipedia.org/wiki/I_Can_Has_Cheezburger%3F',
    mediaType: 'image',
    publishedAt: '2007-01-11',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.5, reasoning: 'A known site aggregating anonymous community submissions.' },
      { axis: 'reach', value: 0.7, reasoning: 'Defined a whole genre of internet humor.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'The image-macro format itself.' },
      { axis: 'diplomatic_cross_boundary', value: 0.55, reasoning: 'The macro format spread to many languages.' },
      { axis: 'diplomatic_authenticity', value: 0.35, reasoning: 'Light entertainment, no cultural grounding.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Built entirely on user submission and remix.' },
    ],
  },
  {
    externalId: 'e2-keyboard-cat',
    title: 'Keyboard Cat (2007)',
    description: 'A 1984 home video of a cat “playing” keyboard, rediscovered as the web’s play-off meme.',
    url: 'https://en.wikipedia.org/wiki/Keyboard_Cat',
    mediaType: 'video',
    publishedAt: '2007-06-07',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.7, reasoning: 'Known original creator; reuse complicates attribution.' },
      { axis: 'reach', value: 0.6, reasoning: 'A canonical meme template.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'Lo-fi home video.' },
      { axis: 'diplomatic_cross_boundary', value: 0.45, reasoning: 'Globally legible, language-free humor.' },
      { axis: 'diplomatic_authenticity', value: 0.35, reasoning: 'Novelty rather than cultural expression.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'A reusable template for endless remixes.' },
    ],
  },
  {
    externalId: 'e2-susan-boyle',
    title: 'Susan Boyle, Britain’s Got Talent (2009)',
    description: 'A talent-show audition whose clip became one of the fastest-spreading videos of its time — TV virality entering the platform age.',
    url: 'https://en.wikipedia.org/wiki/Susan_Boyle',
    mediaType: 'video',
    publishedAt: '2009-04-11',
    originCountryCodes: ['GB'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Clear performer and broadcast origin.' },
      { axis: 'reach', value: 0.85, reasoning: 'Hundreds of millions of views within days.' },
      { axis: 'aesthetic_signal', value: 0.5, reasoning: 'Broadcast talent-show production.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'A globally shared emotional moment.' },
      { axis: 'diplomatic_authenticity', value: 0.7, reasoning: 'Authentic performance and story.' },
      { axis: 'diplomatic_reciprocity', value: 0.3, reasoning: 'Mostly one-way viewing.' },
    ],
  },
  {
    externalId: 'e2-david-after-dentist',
    title: 'David After Dentist (2009)',
    description: 'A father’s clip of his son after a dental procedure — emblematic of family-uploaded viral video.',
    url: 'https://en.wikipedia.org/wiki/David_After_Dentist',
    mediaType: 'video',
    publishedAt: '2009-01-30',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Known family creator.' },
      { axis: 'reach', value: 0.65, reasoning: 'A canonical viral clip.' },
      { axis: 'aesthetic_signal', value: 0.2, reasoning: 'Phone-camera home video.' },
      { axis: 'diplomatic_cross_boundary', value: 0.45, reasoning: 'Universally legible.' },
      { axis: 'diplomatic_authenticity', value: 0.65, reasoning: 'Authentic candid moment.' },
      { axis: 'diplomatic_reciprocity', value: 0.3, reasoning: 'One-way viewing with light remixing.' },
    ],
  },
  {
    externalId: 'e2-auto-tune-the-news',
    title: 'Auto-Tune the News (Gregory Brothers, 2009)',
    description: 'A series that musically remixed news clips, pioneering the songified-media format and the later “Bed Intruder” hit.',
    url: 'https://en.wikipedia.org/wiki/The_Gregory_Brothers',
    mediaType: 'video',
    publishedAt: '2009-04-12',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Clear authorship, built from others’ source clips.' },
      { axis: 'reach', value: 0.6, reasoning: 'Defined a remix format adopted widely.' },
      { axis: 'aesthetic_signal', value: 0.75, reasoning: 'A signature songify-the-news aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.4, reasoning: 'Rooted in US news cycles.' },
      { axis: 'diplomatic_authenticity', value: 0.55, reasoning: 'Authentic original craft using found material.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'Built on and fed remix culture.' },
    ],
  },
  {
    externalId: 'e2-bed-intruder',
    title: 'Bed Intruder Song (2010)',
    description: 'An Auto-Tuned news interview that became a charting single — a high point of the songified-news meme.',
    url: 'https://en.wikipedia.org/wiki/Bed_Intruder_Song',
    mediaType: 'video',
    publishedAt: '2010-07-30',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.7, reasoning: 'Known remixers; source subject did not consent to the format.' },
      { axis: 'reach', value: 0.7, reasoning: 'Charted on the Billboard Hot 100.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'The songify aesthetic at its peak.' },
      { axis: 'diplomatic_cross_boundary', value: 0.4, reasoning: 'A US-context phenomenon.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'Raises real questions of exploitation and consent.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'Heavily remixed and covered.' },
    ],
  },
  {
    externalId: 'e2-double-rainbow',
    title: 'Double Rainbow (2010)',
    description: 'A hiker’s ecstatic reaction to a rainbow that became a viral sensation and Auto-Tune remix.',
    url: 'https://en.wikipedia.org/wiki/Double_Rainbow_(viral_video)',
    mediaType: 'video',
    publishedAt: '2010-07-03',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Known single creator.' },
      { axis: 'reach', value: 0.6, reasoning: 'A canonical viral clip.' },
      { axis: 'aesthetic_signal', value: 0.3, reasoning: 'Unstyled camcorder footage.' },
      { axis: 'diplomatic_cross_boundary', value: 0.4, reasoning: 'Universally legible wonder.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'Genuine, unperformed emotion.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Spawned remixes and parodies.' },
    ],
  },
  {
    externalId: 'e2-old-spice',
    title: 'Old Spice: “The Man Your Man Could Smell Like” (2010)',
    description: 'An ad campaign whose real-time video responses pioneered brand-as-creator social interaction.',
    url: 'https://en.wikipedia.org/wiki/Old_Spice#The_Man_Your_Man_Could_Smell_Like',
    mediaType: 'video',
    publishedAt: '2010-02-04',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear advertiser/agency origin.' },
      { axis: 'reach', value: 0.75, reasoning: 'A landmark viral marketing campaign.' },
      { axis: 'aesthetic_signal', value: 0.8, reasoning: 'A distinctive, much-imitated style.' },
      { axis: 'diplomatic_cross_boundary', value: 0.55, reasoning: 'Globally circulated marketing.' },
      { axis: 'diplomatic_authenticity', value: 0.3, reasoning: 'Commercial content, not cultural expression.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Real-time personalized video replies — unusually interactive.' },
    ],
  },
  {
    externalId: 'e2-united-breaks-guitars',
    title: 'United Breaks Guitars (2009)',
    description: 'A musician’s protest song over a broken guitar that became a consumer-power viral case study.',
    url: 'https://en.wikipedia.org/wiki/United_Breaks_Guitars',
    mediaType: 'video',
    publishedAt: '2009-07-06',
    originCountryCodes: ['CA'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear single author.' },
      { axis: 'reach', value: 0.6, reasoning: 'A widely cited consumer-advocacy viral hit.' },
      { axis: 'aesthetic_signal', value: 0.5, reasoning: 'A competent music-video format.' },
      { axis: 'diplomatic_cross_boundary', value: 0.4, reasoning: 'A North American business story.' },
      { axis: 'diplomatic_authenticity', value: 0.7, reasoning: 'An authentic grievance, well-crafted.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Prompted corporate response and imitators.' },
    ],
  },
  {
    externalId: 'e2-nyan-cat',
    youtubeId: 'QH2-TGUlwu4',
    title: 'Nyan Cat (2011)',
    description: 'A looping pixel-cat animation set to a Japanese Vocaloid song — a layered-origin meme blending US art and Japanese audio.',
    url: 'https://en.wikipedia.org/wiki/Nyan_Cat',
    mediaType: 'video',
    publishedAt: '2011-04-05',
    originCountryCodes: ['JP', 'US'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.55, reasoning: 'US animation plus a Japanese Vocaloid track — layered, semi-anonymous.' },
      { axis: 'reach', value: 0.65, reasoning: 'A globally recognized meme.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'An iconic pixel-art-and-chiptune look.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'A genuinely cross-cultural meme object.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'Playful pastiche rather than cultural depth.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Endlessly remixed worldwide.' },
    ],
  },
  {
    externalId: 'e2-kony-2012',
    title: 'Kony 2012 (2012)',
    description: 'An advocacy film that became the fastest-spreading viral video to that point — and a case study in oversimplified cross-cultural narrative.',
    url: 'https://en.wikipedia.org/wiki/Kony_2012',
    mediaType: 'video',
    publishedAt: '2012-03-05',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear NGO origin (Invisible Children).' },
      { axis: 'reach', value: 0.85, reasoning: '100M views in days — unprecedented speed.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'Polished advocacy-documentary style.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'A US narrative about Uganda spread globally.' },
      { axis: 'diplomatic_authenticity', value: 0.25, reasoning: 'Widely criticized for flattening African agency and context.' },
      { axis: 'diplomatic_reciprocity', value: 0.2, reasoning: 'One-directional Western framing.' },
    ],
  },
  {
    externalId: 'e2-where-the-hell-is-matt',
    title: 'Where the Hell is Matt? (2008)',
    description: 'A man dancing badly in dozens of countries — an early, earnest icon of global cross-cultural connection online.',
    url: 'https://en.wikipedia.org/wiki/Matt_Harding',
    mediaType: 'video',
    publishedAt: '2008-06-20',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Clear single creator.' },
      { axis: 'reach', value: 0.6, reasoning: 'A beloved, widely shared series.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'A simple but distinctive globe-trotting format.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'Literally filmed across cultures with local participants.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'Earnest, if light, cross-cultural participation.' },
      { axis: 'diplomatic_reciprocity', value: 0.7, reasoning: 'Locals around the world danced together with him.' },
    ],
  },
  {
    externalId: 'e2-jk-wedding-dance',
    title: 'JK Wedding Entrance Dance (2009)',
    description: 'A choreographed wedding entrance that went viral and turned a song back into a chart hit — virality feeding back to the source.',
    url: 'https://en.wikipedia.org/wiki/JK_Wedding_Entrance_Dance',
    mediaType: 'video',
    publishedAt: '2009-07-19',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Known wedding party creators.' },
      { axis: 'reach', value: 0.6, reasoning: 'A canonical viral video.' },
      { axis: 'aesthetic_signal', value: 0.45, reasoning: 'Camcorder footage of a choreographed moment.' },
      { axis: 'diplomatic_cross_boundary', value: 0.4, reasoning: 'Universally legible celebration.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'A genuine personal event.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'Revived sales of the original song.' },
    ],
  },
  {
    externalId: 'e2-rebecca-black-friday',
    title: 'Rebecca Black, “Friday” (2011)',
    description: 'A pay-to-produce pop song that went viral as “the worst song ever” — an early case of algorithmic infamy.',
    url: 'https://en.wikipedia.org/wiki/Friday_(Rebecca_Black_song)',
    mediaType: 'video',
    publishedAt: '2011-02-10',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Clear artist and production company.' },
      { axis: 'reach', value: 0.7, reasoning: 'A defining viral-infamy moment.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'Generic teen-pop production.' },
      { axis: 'diplomatic_cross_boundary', value: 0.45, reasoning: 'Globally mocked and shared.' },
      { axis: 'diplomatic_authenticity', value: 0.3, reasoning: 'Manufactured pop, embraced ironically.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Massive parody and remix response.' },
    ],
  },
  {
    externalId: 'e2-justin-bieber-baby',
    title: 'Justin Bieber, “Baby” (2010)',
    description: 'A YouTube-discovered teen star’s signature single — the platform converting attention into global stardom.',
    url: 'https://en.wikipedia.org/wiki/Baby_(Justin_Bieber_song)',
    mediaType: 'video',
    publishedAt: '2010-02-19',
    originCountryCodes: ['CA'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear artist and label.' },
      { axis: 'reach', value: 0.9, reasoning: 'For years the most-viewed video on YouTube.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'Polished mainstream pop.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'Global pop reach.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'Industry pop product.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'A vast fan and parody ecosystem.' },
    ],
  },
  {
    externalId: 'e2-leave-britney-alone',
    title: '“Leave Britney Alone” (Chris Crocker, 2007)',
    description: 'An emotional vlog defending Britney Spears — an early icon of the confessional, parasocial creator.',
    url: 'https://en.wikipedia.org/wiki/Chris_Crocker',
    mediaType: 'video',
    publishedAt: '2007-09-10',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Clear single creator.' },
      { axis: 'reach', value: 0.6, reasoning: 'A canonical early-vlog moment.' },
      { axis: 'aesthetic_signal', value: 0.5, reasoning: 'The raw webcam-confessional aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.35, reasoning: 'A US-celebrity-culture event.' },
      { axis: 'diplomatic_authenticity', value: 0.55, reasoning: 'Genuine emotion, later reframed by the creator.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Heavily parodied.' },
    ],
  },
  {
    externalId: 'e2-call-me-maybe',
    title: 'Carly Rae Jepsen, “Call Me Maybe” (2012)',
    description: 'A pop song propelled to global ubiquity by celebrity lip-sync videos — virality through participatory covers.',
    url: 'https://en.wikipedia.org/wiki/Call_Me_Maybe',
    mediaType: 'video',
    publishedAt: '2012-03-01',
    originCountryCodes: ['CA'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear artist and label.' },
      { axis: 'reach', value: 0.85, reasoning: 'A global number-one hit.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'Bright, hooky mainstream pop.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'Worldwide chart success.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'Polished pop product.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Spread through countless fan and celebrity cover videos.' },
    ],
  },
  {
    externalId: 'e2-somebody-that-i-used-to-know',
    title: 'Gotye, “Somebody That I Used to Know” (2011)',
    description: 'A global hit whose famous video and many covers exemplified the early-2010s cross-border music economy.',
    url: 'https://en.wikipedia.org/wiki/Somebody_That_I_Used_to_Know',
    mediaType: 'video',
    publishedAt: '2011-07-05',
    originCountryCodes: ['AU'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear Belgian-Australian artist.' },
      { axis: 'reach', value: 0.85, reasoning: 'A worldwide number-one single.' },
      { axis: 'aesthetic_signal', value: 0.8, reasoning: 'A distinctive stop-motion body-paint video.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'Truly global chart reach.' },
      { axis: 'diplomatic_authenticity', value: 0.65, reasoning: 'A singular, self-authored artistic statement.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'A wave of viral covers, notably Walk Off the Earth.' },
    ],
  },
  {
    externalId: 'e2-minecraft',
    title: 'Minecraft (2011)',
    description: 'An open-ended building game that became a global creative platform and the backbone of a generation of YouTube content.',
    url: 'https://en.wikipedia.org/wiki/Minecraft',
    mediaType: 'mixed',
    publishedAt: '2011-11-18',
    originCountryCodes: ['SE'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear creator and studio (Mojang).' },
      { axis: 'reach', value: 0.95, reasoning: 'The best-selling video game of all time.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'An instantly recognizable blocky aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'A worldwide creative community.' },
      { axis: 'diplomatic_authenticity', value: 0.5, reasoning: 'A culturally neutral sandbox.' },
      { axis: 'diplomatic_reciprocity', value: 0.75, reasoning: 'Built on a massive user-creation and modding economy.' },
    ],
  },
  {
    externalId: 'e2-angry-birds',
    title: 'Angry Birds (2009)',
    description: 'A mobile game that became a global brand — early evidence of the smartphone as a mass cultural platform.',
    url: 'https://en.wikipedia.org/wiki/Angry_Birds',
    mediaType: 'mixed',
    publishedAt: '2009-12-11',
    originCountryCodes: ['FI'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear studio origin (Rovio).' },
      { axis: 'reach', value: 0.85, reasoning: 'Billions of downloads worldwide.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'A globally recognized character design.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'A Finnish IP that became globally ubiquitous.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'Light, culturally neutral entertainment.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'A largely one-way commercial franchise.' },
    ],
  },
  {
    externalId: 'e2-instagram',
    title: 'Instagram (2010)',
    description: 'A photo-sharing app whose filters reshaped global visual culture and the aesthetics of everyday image-making.',
    url: 'https://en.wikipedia.org/wiki/Instagram',
    mediaType: 'image',
    publishedAt: '2010-10-06',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear platform origin.' },
      { axis: 'reach', value: 0.95, reasoning: 'Over a billion users; defined modern visual culture.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'Its filters created a recognizable global look.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'A worldwide image-sharing layer.' },
      { axis: 'diplomatic_authenticity', value: 0.35, reasoning: 'A platform that standardizes and flattens aesthetics.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Broadly participatory by design.' },
    ],
  },
  {
    externalId: 'e2-battle-at-kruger',
    title: 'Battle at Kruger (2007)',
    description: 'Amateur safari footage of a lion-buffalo-crocodile standoff that became one of YouTube’s most-watched videos.',
    url: 'https://en.wikipedia.org/wiki/Battle_at_Kruger',
    mediaType: 'video',
    publishedAt: '2007-05-03',
    originCountryCodes: ['ZA'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.8, reasoning: 'Tourist footage with later-confirmed authorship.' },
      { axis: 'reach', value: 0.7, reasoning: 'Tens of millions of views; a TV documentary followed.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'Raw handheld safari footage.' },
      { axis: 'diplomatic_cross_boundary', value: 0.65, reasoning: 'A South African scene watched worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.7, reasoning: 'Unstaged, authentic wildlife capture.' },
      { axis: 'diplomatic_reciprocity', value: 0.3, reasoning: 'Largely one-way viewing.' },
    ],
  },
  {
    externalId: 'e2-kolaveri-di',
    title: '“Why This Kolaveri Di” (2011)',
    description: 'A Tamil-English song that became India’s first true YouTube viral smash — South-Asian pop traveling natively online.',
    url: 'https://en.wikipedia.org/wiki/Why_This_Kolaveri_Di',
    mediaType: 'video',
    publishedAt: '2011-11-16',
    originCountryCodes: ['IN'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear Tamil-cinema origin.' },
      { axis: 'reach', value: 0.75, reasoning: 'India’s first massive YouTube viral hit.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'A distinctive “Tanglish” pop sound.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'Crossed from regional to global audiences online.' },
      { axis: 'diplomatic_authenticity', value: 0.8, reasoning: 'Rooted in Tamil linguistic and musical specificity.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'A wave of covers and responses.' },
    ],
  },
  {
    externalId: 'e2-girls-generation-gee',
    title: 'Girls’ Generation, “Gee” (2009)',
    description: 'A defining second-generation K-pop hit that helped seed the global Hallyu wave before its platform peak.',
    url: 'https://en.wikipedia.org/wiki/Gee_(song)',
    mediaType: 'video',
    publishedAt: '2009-01-05',
    originCountryCodes: ['KR'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear SM Entertainment / Korean origin.' },
      { axis: 'reach', value: 0.7, reasoning: 'A landmark of K-pop’s pre-global-peak rise.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'The polished second-gen K-pop aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'Early cross-Asian and diaspora reach.' },
      { axis: 'diplomatic_authenticity', value: 0.7, reasoning: 'A specific, industrialized Korean idol form.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'Cultivated active international fandoms.' },
    ],
  },
  {
    externalId: 'e2-wonder-girls-nobody',
    title: 'Wonder Girls, “Nobody” (2008)',
    description: 'A K-pop hit that became one of the first to chart on the US Billboard Hot 100 — an early Hallyu border-crossing.',
    url: 'https://en.wikipedia.org/wiki/Nobody_(Wonder_Girls_song)',
    mediaType: 'video',
    publishedAt: '2008-09-22',
    originCountryCodes: ['KR'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear JYP / Korean origin.' },
      { axis: 'reach', value: 0.6, reasoning: 'An early K-pop entry onto the US chart.' },
      { axis: 'aesthetic_signal', value: 0.75, reasoning: 'A retro-styled K-pop sound and look.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'A deliberate, early US crossover attempt.' },
      { axis: 'diplomatic_authenticity', value: 0.65, reasoning: 'Korean idol-pop adapting toward Western markets.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'Built bilateral fan engagement.' },
    ],
  },
  {
    externalId: 'e2-kseniya-simonova',
    title: 'Kseniya Simonova, Ukraine’s Got Talent sand art (2009)',
    description: 'A live sand-animation performance about WWII that became a globally shared emotional artifact.',
    url: 'https://en.wikipedia.org/wiki/Kseniya_Simonova',
    mediaType: 'video',
    publishedAt: '2009-08-02',
    originCountryCodes: ['UA'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear performer and broadcast origin.' },
      { axis: 'reach', value: 0.6, reasoning: 'Tens of millions of views worldwide.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'A striking, singular live-art form.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'A Ukrainian historical narrative shared globally.' },
      { axis: 'diplomatic_authenticity', value: 0.85, reasoning: 'Deeply rooted in national memory.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Largely one-way, deeply received.' },
    ],
  },
  {
    externalId: 'e2-akb48',
    title: 'AKB48 (debut 2005)',
    description: 'A Japanese idol group built on a “theater + fan participation” model — a distinctive, highly participatory pop formation.',
    url: 'https://en.wikipedia.org/wiki/AKB48',
    mediaType: 'video',
    publishedAt: '2005-12-08',
    originCountryCodes: ['JP'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear, highly specific Japanese idol-industry origin.' },
      { axis: 'reach', value: 0.7, reasoning: 'Dominant in Japan with significant Asian reach.' },
      { axis: 'aesthetic_signal', value: 0.75, reasoning: 'A recognizable idol-group form.' },
      { axis: 'diplomatic_cross_boundary', value: 0.5, reasoning: 'Spawned sister groups across Asia.' },
      { axis: 'diplomatic_authenticity', value: 0.7, reasoning: 'A culturally specific idol model.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Fan-election and theater formats are intensely participatory.' },
    ],
  },
];
