import type { SeedArtifact } from './types';
/**
 * Era 2024–2026 — the AI-native frontier (the tunnel's cavernous near end): generative video/music,
 * AI "slop," activist and election deepfakes, and the live cultural touchstones of 2024–25. Draft
 * scores, v1.2 construct (origin: high = clear; anonymous AI artifacts score low).
 */
const ERA = '2024–2026';
export const ERA_2024_2026: SeedArtifact[] = [
  {
    externalId: 'e5-sora',
    title: 'OpenAI Sora (2024)',
    description: 'A text-to-video model whose first demos collapsed the cost of cinematic footage — the moving-image floor dropping toward zero.',
    url: 'https://en.wikipedia.org/wiki/Sora_(text-to-video_model)',
    mediaType: 'video',
    publishedAt: '2024-02-15',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Clear lab origin; its footage has diffuse, trained-on origin.' },
      { axis: 'reach', value: 0.8, reasoning: 'Reset global expectations for generated video.' },
      { axis: 'aesthetic_signal', value: 0.65, reasoning: 'Recognizable early-model motion fingerprints.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'A globally consequential capability.' },
      { axis: 'diplomatic_authenticity', value: 0.25, reasoning: 'Synthesizes others’ footage without provenance.' },
      { axis: 'diplomatic_reciprocity', value: 0.2, reasoning: 'A one-way generation tool.' },
    ],
  },
  {
    externalId: 'e5-ghibli-chatgpt-trend',
    title: 'The Studio Ghibli ChatGPT image trend (2025)',
    description: 'GPT-4o’s image tool let millions restyle photos as “Ghibli” art overnight — a mass act of style appropriation that strained the meaning of origin.',
    url: 'https://en.wikipedia.org/wiki/Studio_Ghibli#Artificial_intelligence',
    mediaType: 'image',
    publishedAt: '2025-03-26',
    originCountryCodes: ['US', 'JP'],
    aiMediation: 'ai_generated',
    authorshipClass: 'ambiguous_unattributable',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.3, reasoning: 'Outputs impersonate a studio’s style with no real Ghibli origin.' },
      { axis: 'reach', value: 0.85, reasoning: 'A near-instant global trend; servers buckled.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'A borrowed, instantly recognizable house style.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'A Japanese aesthetic mass-applied worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.15, reasoning: 'Appropriates a tradition its source publicly opposes.' },
      { axis: 'diplomatic_reciprocity', value: 0.2, reasoning: 'Extraction of a style, not exchange with it.' },
    ],
  },
  {
    externalId: 'e5-suno',
    title: 'Suno AI music (2024)',
    description: 'A text-to-song model that made full, plausible tracks from a prompt — generative music reaching the public, and the courts.',
    url: 'https://en.wikipedia.org/wiki/Suno_AI',
    mediaType: 'audio',
    publishedAt: '2024-03-21',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.8, reasoning: 'A clear company; songs carry diffuse trained-on origin.' },
      { axis: 'reach', value: 0.7, reasoning: 'Brought generative music to a wide public.' },
      { axis: 'aesthetic_signal', value: 0.55, reasoning: 'Competent pastiche across genres.' },
      { axis: 'diplomatic_cross_boundary', value: 0.65, reasoning: 'A globally used tool.' },
      { axis: 'diplomatic_authenticity', value: 0.2, reasoning: 'Trained on uncredited recordings, now litigated.' },
      { axis: 'diplomatic_reciprocity', value: 0.2, reasoning: 'One-way generation.' },
    ],
  },
  {
    externalId: 'e5-veo-3',
    title: 'Google Veo 3 (2025)',
    description: 'A generative-video model with synchronized audio whose realism made AI clips routinely indistinguishable in social feeds.',
    url: 'https://en.wikipedia.org/wiki/Veo_(text-to-video_model)',
    mediaType: 'video',
    publishedAt: '2025-05-20',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Clear lab origin; diffuse output provenance.' },
      { axis: 'reach', value: 0.75, reasoning: 'Flooded feeds with convincing AI video.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'Higher realism, fewer obvious fingerprints.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'A globally consequential capability.' },
      { axis: 'diplomatic_authenticity', value: 0.2, reasoning: 'Erodes the evidentiary value of video.' },
      { axis: 'diplomatic_reciprocity', value: 0.2, reasoning: 'A one-way generation tool.' },
    ],
  },
  {
    externalId: 'e5-deepseek',
    title: 'DeepSeek (2025)',
    description: 'A Chinese open-weight model whose performance and low cost shocked markets — a sovereignty moment for AI capability.',
    url: 'https://en.wikipedia.org/wiki/DeepSeek',
    mediaType: 'text',
    publishedAt: '2025-01-20',
    originCountryCodes: ['CN'],
    aiMediation: 'ai_generated',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Clear Chinese lab origin; open weights scatter downstream use.' },
      { axis: 'reach', value: 0.8, reasoning: 'A global shock to the AI industry and markets.' },
      { axis: 'aesthetic_signal', value: 0.3, reasoning: 'A model, not an aesthetic object.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'Reframed the geopolitics of AI capability.' },
      { axis: 'diplomatic_authenticity', value: 0.3, reasoning: 'Capability artifact rather than cultural expression.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Open release invites global building-upon.' },
    ],
  },
  {
    externalId: 'e5-italian-brainrot',
    title: '“Italian brainrot” AI memes (2025)',
    description: 'Absurd AI-generated creatures with fake-Italian names (Tralalero Tralala, Ballerina Cappuccina) that became a global Gen-Alpha meme universe of no real origin.',
    url: 'https://en.wikipedia.org/wiki/Italian_brainrot',
    mediaType: 'video',
    publishedAt: '2025-02-01',
    originCountryCodes: ['IT'],
    aiMediation: 'ai_generated',
    authorshipClass: 'ambiguous_unattributable',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.2, reasoning: 'Machine-generated, communally extended; no real authors or origin.' },
      { axis: 'reach', value: 0.8, reasoning: 'A vast global Gen-Alpha meme phenomenon.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'A distinctive AI-surreal look and mock-Italian audio.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'Spread across the world’s youth internet.' },
      { axis: 'diplomatic_authenticity', value: 0.1, reasoning: 'Mock-Italian nonsense, no cultural grounding.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'Communally remixed into an expanding canon.' },
    ],
  },
  {
    externalId: 'e5-all-eyes-on-rafah',
    title: '“All Eyes on Rafah” AI image (2024)',
    description: 'An AI-generated protest image shared by tens of millions on Instagram — a sanitized, originless graphic standing in for a real catastrophe.',
    url: 'https://en.wikipedia.org/wiki/All_Eyes_on_Rafah',
    mediaType: 'image',
    publishedAt: '2024-05-28',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'ambiguous_unattributable',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.2, reasoning: 'An AI image of unclear authorship, detached from the event it represents.' },
      { axis: 'reach', value: 0.9, reasoning: 'Shared ~47 million times in days.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'Deliberately frictionless, shareable AI graphic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'A global act of networked solidarity.' },
      { axis: 'diplomatic_authenticity', value: 0.2, reasoning: 'A synthetic image substituting for real documentation.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Mass resharing, little reciprocal exchange.' },
    ],
  },
  {
    externalId: 'e5-shrimp-jesus',
    title: '“Shrimp Jesus” / AI Facebook slop (2024)',
    description: 'Surreal AI images engineered for engagement that flooded Facebook — content with no author, audience, or meaning beyond the algorithm.',
    url: 'https://en.wikipedia.org/wiki/AI_slop',
    mediaType: 'image',
    publishedAt: '2024-04-01',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'ambiguous_unattributable',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.15, reasoning: 'Spam-farm output; origin deliberately anonymous.' },
      { axis: 'reach', value: 0.6, reasoning: 'Enormous algorithmic distribution, hollow engagement.' },
      { axis: 'aesthetic_signal', value: 0.3, reasoning: 'Generic, uncanny AI imagery.' },
      { axis: 'diplomatic_cross_boundary', value: 0.5, reasoning: 'A globally visible symptom of feed decay.' },
      { axis: 'diplomatic_authenticity', value: 0.05, reasoning: 'The antithesis of authorship and meaning.' },
      { axis: 'diplomatic_reciprocity', value: 0.05, reasoning: 'No exchange; engagement farming.' },
    ],
  },
  {
    externalId: 'e5-bbl-drizzy',
    title: '“BBL Drizzy” (2024)',
    description: 'An AI-generated soul beat from the Drake–Kendrick feud that producers freely sampled — AI as raw material for human remix.',
    url: 'https://en.wikipedia.org/wiki/BBL_Drizzy',
    mediaType: 'audio',
    publishedAt: '2024-05-06',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.45, reasoning: 'A named creator who generated the beat with AI — layered origin.' },
      { axis: 'reach', value: 0.6, reasoning: 'A widely sampled viral moment in a landmark beef.' },
      { axis: 'aesthetic_signal', value: 0.5, reasoning: 'A faux-vintage soul sound.' },
      { axis: 'diplomatic_cross_boundary', value: 0.45, reasoning: 'A US hip-hop event with global notice.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'AI source reworked through authentic remix culture.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Openly invited communal sampling.' },
    ],
  },
  {
    externalId: 'e5-willys-chocolate-experience',
    title: 'Willy’s Chocolate Experience (2024)',
    description: 'A Glasgow event sold via AI-generated fantasy images that delivered a bleak event in a bare warehouse — a parable of AI marketing versus reality.',
    url: 'https://en.wikipedia.org/wiki/Willy%27s_Chocolate_Experience',
    mediaType: 'image',
    publishedAt: '2024-02-24',
    originCountryCodes: ['GB'],
    aiMediation: 'ai_generated',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.5, reasoning: 'A known organizer using AI promo images of nonexistent scenes.' },
      { axis: 'reach', value: 0.6, reasoning: 'A global news-and-meme story.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'Generic AI fantasy art.' },
      { axis: 'diplomatic_cross_boundary', value: 0.55, reasoning: 'A globally shared cautionary tale.' },
      { axis: 'diplomatic_authenticity', value: 0.15, reasoning: 'AI promises with no real substance behind them.' },
      { axis: 'diplomatic_reciprocity', value: 0.3, reasoning: 'Mostly one-way ridicule.' },
    ],
  },
  {
    externalId: 'e5-taylor-swift-deepfake',
    title: 'Taylor Swift deepfake incident (2024)',
    description: 'Nonconsensual AI images of Taylor Swift that spread on X spurred new legislation — synthetic media as targeted harm.',
    url: 'https://en.wikipedia.org/wiki/Taylor_Swift_deepfake_pornography_controversy',
    mediaType: 'image',
    publishedAt: '2024-01-24',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'ambiguous_unattributable',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.1, reasoning: 'Anonymous, malicious fabrication of a real person.' },
      { axis: 'reach', value: 0.7, reasoning: 'Tens of millions of views before removal; prompted legislation.' },
      { axis: 'aesthetic_signal', value: 0.2, reasoning: 'Fabricated imitation, no authored aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.5, reasoning: 'A globally discussed harm and policy turning point.' },
      { axis: 'diplomatic_authenticity', value: 0.05, reasoning: 'Counterfeit and abusive by intent.' },
      { axis: 'diplomatic_reciprocity', value: 0.05, reasoning: 'No exchange.' },
    ],
  },
  {
    externalId: 'e5-biden-robocall-deepfake',
    title: 'Biden AI robocall, New Hampshire primary (2024)',
    description: 'An AI-voiced robocall impersonating President Biden told voters to stay home — the first prominent US election deepfake.',
    url: 'https://en.wikipedia.org/wiki/2024_New_Hampshire_Democratic_presidential_primary#AI_robocall',
    mediaType: 'audio',
    publishedAt: '2024-01-21',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'ambiguous_unattributable',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.15, reasoning: 'A voice clone of a real leader; origin concealed, later prosecuted.' },
      { axis: 'reach', value: 0.45, reasoning: 'Limited reach but outsized precedent.' },
      { axis: 'aesthetic_signal', value: 0.2, reasoning: 'A plain voice clone.' },
      { axis: 'diplomatic_cross_boundary', value: 0.4, reasoning: 'A globally noted democratic-integrity case.' },
      { axis: 'diplomatic_authenticity', value: 0.05, reasoning: 'Deliberate political forgery.' },
      { axis: 'diplomatic_reciprocity', value: 0.05, reasoning: 'Pure manipulation.' },
    ],
  },
  {
    externalId: 'e5-coca-cola-ai-ad',
    title: 'Coca-Cola AI Christmas ad (2024)',
    description: 'A remake of Coca-Cola’s holiday ad made with generative AI that drew widespread backlash — a brand’s synthetic-nostalgia misstep.',
    url: 'https://en.wikipedia.org/wiki/Coca-Cola#Artificial_intelligence',
    mediaType: 'video',
    publishedAt: '2024-11-15',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.6, reasoning: 'A clear brand using AI to remake its own iconography.' },
      { axis: 'reach', value: 0.6, reasoning: 'A widely covered controversy.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'Uncanny AI-smoothed nostalgia.' },
      { axis: 'diplomatic_cross_boundary', value: 0.55, reasoning: 'A global brand, globally debated.' },
      { axis: 'diplomatic_authenticity', value: 0.2, reasoning: 'Hollowed-out nostalgia, widely rejected as inauthentic.' },
      { axis: 'diplomatic_reciprocity', value: 0.2, reasoning: 'A one-way ad campaign.' },
    ],
  },
  {
    externalId: 'e5-google-ai-overviews',
    title: 'Google AI Overviews “glue on pizza” (2024)',
    description: 'AI search summaries confidently surfacing absurd advice — generative authority detached from any reliable origin.',
    url: 'https://en.wikipedia.org/wiki/AI_Overviews',
    mediaType: 'text',
    publishedAt: '2024-05-23',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.55, reasoning: 'A clear platform, but answers synthesized from unattributed sources.' },
      { axis: 'reach', value: 0.7, reasoning: 'Surfaced atop the world’s dominant search engine.' },
      { axis: 'aesthetic_signal', value: 0.2, reasoning: 'Plain generated summaries.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'A globally deployed change to how knowledge is presented.' },
      { axis: 'diplomatic_authenticity', value: 0.2, reasoning: 'Confident answers decoupled from sourcing.' },
      { axis: 'diplomatic_reciprocity', value: 0.15, reasoning: 'One-way answer delivery.' },
    ],
  },
  {
    externalId: 'e5-brat',
    title: 'Charli XCX, “Brat” summer (2024)',
    description: 'An album whose lime-green branding became a global aesthetic and entered politics — a color and word turned cultural movement.',
    url: 'https://en.wikipedia.org/wiki/Brat_(album)',
    mediaType: 'audio',
    publishedAt: '2024-06-07',
    originCountryCodes: ['GB'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear artist authorship.' },
      { axis: 'reach', value: 0.8, reasoning: 'A defining cultural aesthetic of the year, used in a US campaign.' },
      { axis: 'aesthetic_signal', value: 0.9, reasoning: 'The lime-green “brat” look is instantly legible.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'A globally adopted aesthetic.' },
      { axis: 'diplomatic_authenticity', value: 0.7, reasoning: 'A specific, authored artistic vision.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'A meme-and-remix template the artist encouraged.' },
    ],
  },
  {
    externalId: 'e5-espresso',
    title: 'Sabrina Carpenter, “Espresso” (2024)',
    description: 'The song of summer 2024, propelled by TikTok and a Coachella debut — platform-era pop ubiquity.',
    url: 'https://en.wikipedia.org/wiki/Espresso_(song)',
    mediaType: 'audio',
    publishedAt: '2024-04-11',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear artist and label.' },
      { axis: 'reach', value: 0.85, reasoning: 'A global song-of-the-summer hit.' },
      { axis: 'aesthetic_signal', value: 0.65, reasoning: 'A bright, hooky retro-pop sound.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'A worldwide chart hit.' },
      { axis: 'diplomatic_authenticity', value: 0.45, reasoning: 'Polished mainstream pop.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'Driven by TikTok participation.' },
    ],
  },
  {
    externalId: 'e5-not-like-us',
    title: 'Kendrick Lamar, “Not Like Us” (2024)',
    description: 'A diss track that became a cultural event and a Super Bowl halftime centerpiece — the apex of the year’s biggest rap feud.',
    url: 'https://en.wikipedia.org/wiki/Not_Like_Us',
    mediaType: 'audio',
    publishedAt: '2024-05-04',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Unmistakable single-artist authorship.' },
      { axis: 'reach', value: 0.85, reasoning: 'A number one, multi-Grammy, Super Bowl performance.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'A singular voice and West-Coast sound.' },
      { axis: 'diplomatic_cross_boundary', value: 0.55, reasoning: 'A deeply US hip-hop event with global attention.' },
      { axis: 'diplomatic_authenticity', value: 0.85, reasoning: 'Rooted in a specific cultural and personal context.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'A vast participatory response, mostly domestic.' },
    ],
  },
  {
    externalId: 'e5-hawk-tuah',
    title: '“Hawk Tuah” (2024)',
    description: 'A street-interview clip that turned a stranger into an overnight celebrity and brand — the speed and volatility of 2024 virality.',
    url: 'https://en.wikipedia.org/wiki/Hawk_Tuah_girl',
    mediaType: 'video',
    publishedAt: '2024-06-11',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.65, reasoning: 'A street-interview subject, suddenly the center of an industry.' },
      { axis: 'reach', value: 0.7, reasoning: 'An overnight global meme and media story.' },
      { axis: 'aesthetic_signal', value: 0.25, reasoning: 'A candid street clip.' },
      { axis: 'diplomatic_cross_boundary', value: 0.4, reasoning: 'A US-internet phenomenon.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'Authentic accident turned managed brand.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'A frenzy of reposts and cash-ins.' },
    ],
  },
  {
    externalId: 'e5-very-demure',
    title: '“Very demure, very mindful” (Jools Lebron, 2024)',
    description: 'A creator’s catchphrase that became a national meme and a lesson in who profits from a viral phrase.',
    url: 'https://en.wikipedia.org/wiki/Very_demure,_very_mindful',
    mediaType: 'video',
    publishedAt: '2024-08-01',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.7, reasoning: 'A clear creator, with a trademark dispute over her own phrase.' },
      { axis: 'reach', value: 0.65, reasoning: 'A defining late-2024 meme.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'A spoken catchphrase format.' },
      { axis: 'diplomatic_cross_boundary', value: 0.35, reasoning: 'A US-centric phenomenon.' },
      { axis: 'diplomatic_authenticity', value: 0.55, reasoning: 'Authentic voice, contested ownership.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Endlessly imitated.' },
    ],
  },
  {
    externalId: 'e5-chappell-roan',
    title: 'Chappell Roan breakthrough (2024)',
    description: 'A drag-influenced pop persona that broke through via festival and streaming virality — the year’s defining new-star ascent.',
    url: 'https://en.wikipedia.org/wiki/Chappell_Roan',
    mediaType: 'audio',
    publishedAt: '2024-04-05',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear artist authorship.' },
      { axis: 'reach', value: 0.75, reasoning: 'A breakout year with record festival crowds.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'A vivid, drag-inflected visual identity.' },
      { axis: 'diplomatic_cross_boundary', value: 0.55, reasoning: 'Growing international reach.' },
      { axis: 'diplomatic_authenticity', value: 0.8, reasoning: 'A specific, authored queer-pop vision.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'A devoted, participatory fandom.' },
    ],
  },
  {
    externalId: 'e5-skibidi-toilet',
    title: 'Skibidi Toilet (2023–2024)',
    description: 'A serialized YouTube/Shorts saga that became the defining Gen-Alpha media object — machine-rendered, community-extended storytelling.',
    url: 'https://en.wikipedia.org/wiki/Skibidi_Toilet',
    mediaType: 'video',
    publishedAt: '2024-01-01',
    originCountryCodes: ['GE'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.7, reasoning: 'A known creator (DaFuq!?Boom!), widely imitated.' },
      { axis: 'reach', value: 0.85, reasoning: 'Tens of billions of views; a generational phenomenon.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'A distinctive game-engine-rendered style.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'A worldwide youth phenomenon.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'Absurdist serial entertainment.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'A huge fan-extension and meme ecosystem.' },
    ],
  },
  {
    externalId: 'e5-chill-guy',
    title: '“Chill Guy” (2024)',
    description: 'A laid-back cartoon dog by a Mexican artist that became a global reaction meme — and a copyright-claim controversy.',
    url: 'https://en.wikipedia.org/wiki/Chill_Guy',
    mediaType: 'image',
    publishedAt: '2024-11-01',
    originCountryCodes: ['MX'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.7, reasoning: 'A clear original artist whose control was tested by mass meme use.' },
      { axis: 'reach', value: 0.7, reasoning: 'A global late-2024 reaction meme.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'A simple, recognizable character.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'A Mexican artist’s creation embraced worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.5, reasoning: 'Authentic origin, strained by commercial misuse.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Mass remixing, contested credit.' },
    ],
  },
  {
    externalId: 'e5-apt',
    youtubeId: 'ekr2nIex040',
    title: 'ROSÉ & Bruno Mars, “APT.” (2024)',
    description: 'A K-pop-meets-US pop smash built on a Korean drinking game — a high-reciprocity East-West collaboration.',
    url: 'https://en.wikipedia.org/wiki/Apt._(song)',
    mediaType: 'video',
    publishedAt: '2024-10-18',
    originCountryCodes: ['KR', 'US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'A clear KR–US collaboration.' },
      { axis: 'reach', value: 0.9, reasoning: 'A global top-of-the-charts hit.' },
      { axis: 'aesthetic_signal', value: 0.8, reasoning: 'A bright, hooky cross-pollinated pop sound.' },
      { axis: 'diplomatic_cross_boundary', value: 0.9, reasoning: 'Korean and US pop meeting at the top of global charts.' },
      { axis: 'diplomatic_authenticity', value: 0.7, reasoning: 'Built on a real Korean social game, genuinely co-created.' },
      { axis: 'diplomatic_reciprocity', value: 0.75, reasoning: 'A true two-way collaboration.' },
    ],
  },
  {
    externalId: 'e5-moo-deng',
    title: 'Moo Deng, the pygmy hippo (2024)',
    description: 'A Thai zoo’s baby hippo that became a global meme and soft-power icon — small-nation charisma traveling worldwide.',
    url: 'https://en.wikipedia.org/wiki/Moo_Deng',
    mediaType: 'image',
    publishedAt: '2024-09-01',
    originCountryCodes: ['TH'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.8, reasoning: 'A specific Thai zoo, amplified by countless posters.' },
      { axis: 'reach', value: 0.7, reasoning: 'A global meme and tourism draw.' },
      { axis: 'aesthetic_signal', value: 0.45, reasoning: 'Candid animal photos and clips.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'A Thai phenomenon embraced worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'Authentic, if commercialized, local origin.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'Global fan art and reposting.' },
    ],
  },
  {
    externalId: 'e5-labubu',
    title: 'Labubu / Pop Mart craze (2024)',
    description: 'A Chinese designer-toy character that became a worldwide collectible craze — Chinese consumer culture as global soft power.',
    url: 'https://en.wikipedia.org/wiki/Labubu',
    mediaType: 'image',
    publishedAt: '2024-06-01',
    originCountryCodes: ['CN'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'A clear designer and company (Pop Mart).' },
      { axis: 'reach', value: 0.75, reasoning: 'A global collecting frenzy.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'A distinctive toothy character design.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'A Chinese IP achieving worldwide demand.' },
      { axis: 'diplomatic_authenticity', value: 0.55, reasoning: 'A designed product, genuinely originated in China.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'A global trading-and-unboxing community.' },
    ],
  },
  {
    externalId: 'e5-tyla-water',
    youtubeId: 'XoiOOiuH8iI',
    title: 'Tyla, “Water” (2024 breakout)',
    description: 'A South African amapiano-pop hit and the first Best African Music Performance Grammy — Amapiano crossing fully into global pop.',
    url: 'https://en.wikipedia.org/wiki/Water_(Tyla_song)',
    mediaType: 'audio',
    publishedAt: '2024-02-04',
    originCountryCodes: ['ZA'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear South African artist.' },
      { axis: 'reach', value: 0.8, reasoning: 'A global hit and Grammy winner.' },
      { axis: 'aesthetic_signal', value: 0.8, reasoning: 'A distinctive amapiano-pop sound and dance.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'Amapiano reaching the global mainstream.' },
      { axis: 'diplomatic_authenticity', value: 0.8, reasoning: 'Rooted in South African musical specificity.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'A global dance-challenge response.' },
    ],
  },
  {
    externalId: 'e5-squid-game-2',
    title: 'Squid Game season 2 (2024)',
    description: 'One of Netflix’s biggest launches ever — Korean storytelling sustaining its place at the center of global streaming.',
    url: 'https://en.wikipedia.org/wiki/Squid_Game_season_2',
    mediaType: 'video',
    publishedAt: '2024-12-26',
    originCountryCodes: ['KR'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear Korean authorship and production.' },
      { axis: 'reach', value: 0.9, reasoning: 'A record-setting Netflix launch.' },
      { axis: 'aesthetic_signal', value: 0.9, reasoning: 'A continued, iconic visual world.' },
      { axis: 'diplomatic_cross_boundary', value: 0.9, reasoning: 'Korean specificity at the global center again.' },
      { axis: 'diplomatic_authenticity', value: 0.8, reasoning: 'Sustains its grounded social critique.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'A renewed global meme-and-response wave.' },
    ],
  },
  {
    externalId: 'e5-black-myth-wukong',
    title: 'Black Myth: Wukong (2024)',
    description: 'A blockbuster Chinese action game drawn from Journey to the West — a landmark of Chinese cultural IP achieving global AAA success.',
    url: 'https://en.wikipedia.org/wiki/Black_Myth:_Wukong',
    mediaType: 'mixed',
    publishedAt: '2024-08-20',
    originCountryCodes: ['CN'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear Chinese studio origin (Game Science).' },
      { axis: 'reach', value: 0.8, reasoning: 'Among the fastest-selling games of the year.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'A lavish, distinctive mythic style.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'A Chinese myth reaching a global gaming audience.' },
      { axis: 'diplomatic_authenticity', value: 0.8, reasoning: 'Deeply rooted in a Chinese literary classic.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'Spurred global interest in its source mythology.' },
    ],
  },
  {
    externalId: 'e5-man-in-finance',
    title: '“Looking for a man in finance” (Megan Boni, 2024)',
    description: 'A 19-second a-cappella TikTok that became a remixed global song — a hook spun into countless professional remixes.',
    url: 'https://en.wikipedia.org/wiki/Man_in_Finance',
    mediaType: 'audio',
    publishedAt: '2024-04-29',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.75, reasoning: 'A clear creator whose clip producers raced to remix.' },
      { axis: 'reach', value: 0.65, reasoning: 'A global meme and charting remix.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'An a-cappella phone clip turned dance track.' },
      { axis: 'diplomatic_cross_boundary', value: 0.5, reasoning: 'Remixed by DJs worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.45, reasoning: 'A joke that became a genuine collaborative track.' },
      { axis: 'diplomatic_reciprocity', value: 0.65, reasoning: 'Built on open, communal remixing.' },
    ],
  },
];
