import type { SeedArtifact } from './types';
/**
 * Era 2012–2018 — the meme-platform era and the first deepfakes: short-form video, challenge memes,
 * algorithmic music crossovers, and the opening of synthetic media. Draft scores, v1.2 construct
 * (origin: high = clear/traceable; deepfakes score low because origin is fabricated).
 */
const ERA = '2012–2018';
export const ERA_2012_2018: SeedArtifact[] = [
  {
    externalId: 'e3-harlem-shake',
    title: 'Harlem Shake (meme, 2013)',
    description: 'A 30-second format spawning hundreds of thousands of copies in weeks — peak template-driven, participatory virality.',
    url: 'https://en.wikipedia.org/wiki/Harlem_Shake_(meme)',
    mediaType: 'video',
    publishedAt: '2013-02-01',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.4, reasoning: 'A diffuse, communally authored format on a borrowed track.' },
      { axis: 'reach', value: 0.8, reasoning: 'Hundreds of thousands of copies within a month.' },
      { axis: 'aesthetic_signal', value: 0.5, reasoning: 'The format itself is the aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'Reproduced in offices and schools worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.3, reasoning: 'A template, detached from the Harlem dance it misnamed.' },
      { axis: 'diplomatic_reciprocity', value: 0.7, reasoning: 'Mass participation was the entire phenomenon.' },
    ],
  },
  {
    externalId: 'e3-vine',
    title: 'Vine (2013)',
    description: 'The six-second looping video app that incubated a generation of creators and short-form comedic grammar.',
    url: 'https://en.wikipedia.org/wiki/Vine_(service)',
    mediaType: 'video',
    publishedAt: '2013-01-24',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear platform origin (Twitter).' },
      { axis: 'reach', value: 0.75, reasoning: 'Defined short-form video before TikTok.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'The six-second loop became its own comedic form.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'A global creator base, US-centric culture.' },
      { axis: 'diplomatic_authenticity', value: 0.45, reasoning: 'A platform layer enabling many authentic creators.' },
      { axis: 'diplomatic_reciprocity', value: 0.65, reasoning: 'A heavily remix-and-reply culture.' },
    ],
  },
  {
    externalId: 'e3-ice-bucket-challenge',
    title: 'ALS Ice Bucket Challenge (2014)',
    description: 'A nominate-a-friend charity challenge that crossed the globe and raised hundreds of millions — participatory philanthropy as meme.',
    url: 'https://en.wikipedia.org/wiki/Ice_Bucket_Challenge',
    mediaType: 'video',
    publishedAt: '2014-07-15',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.45, reasoning: 'A diffuse, collectively propagated challenge.' },
      { axis: 'reach', value: 0.85, reasoning: 'Tens of millions of videos worldwide.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'A simple repeatable action format.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'Practiced across countries and by world figures.' },
      { axis: 'diplomatic_authenticity', value: 0.5, reasoning: 'Genuine cause, sometimes performative participation.' },
      { axis: 'diplomatic_reciprocity', value: 0.8, reasoning: 'The nominate-the-next-person chain is reciprocity by design.' },
    ],
  },
  {
    externalId: 'e3-the-dress',
    title: 'The Dress (#TheDress, 2015)',
    description: 'A photo whose ambiguous colors split the internet — a global perception meme with effectively anonymous origin.',
    url: 'https://en.wikipedia.org/wiki/The_dress',
    mediaType: 'image',
    publishedAt: '2015-02-26',
    originCountryCodes: ['GB'],
    aiMediation: 'human_made',
    authorshipClass: 'ambiguous_unattributable',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.35, reasoning: 'A casually posted photo, origin incidental and near-anonymous.' },
      { axis: 'reach', value: 0.8, reasoning: 'A global overnight phenomenon.' },
      { axis: 'aesthetic_signal', value: 0.3, reasoning: 'An ordinary snapshot; the effect is perceptual.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'A language-free debate shared worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.3, reasoning: 'A perceptual curiosity, not cultural content.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Everyone argued and reposted — broadly participatory.' },
    ],
  },
  {
    externalId: 'e3-deepfakes-origin',
    title: 'Deepfakes (term coined, 2017)',
    description: 'The Reddit-born technique and term for AI face-swapped video — the origin point of synthetic media as a public concern, where origin is fabricated by design.',
    url: 'https://en.wikipedia.org/wiki/Deepfake',
    mediaType: 'video',
    publishedAt: '2017-12-01',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'ambiguous_unattributable',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.15, reasoning: 'The entire technique manufactures false, untraceable origin.' },
      { axis: 'reach', value: 0.6, reasoning: 'Reshaped the public conversation about synthetic media.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'Defined by imitation; no aesthetic of its own.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'A globally relevant capability.' },
      { axis: 'diplomatic_authenticity', value: 0.1, reasoning: 'Built to counterfeit authenticity.' },
      { axis: 'diplomatic_reciprocity', value: 0.1, reasoning: 'No exchange; pure fabrication.' },
    ],
  },
  {
    externalId: 'e3-despacito',
    youtubeId: 'kJQP7kiw5Fk',
    title: 'Luis Fonsi, “Despacito” (2017)',
    description: 'The first video to reach 5 billion views and a Spanish-language song atop the global charts — Latin music’s definitive platform-era crossover.',
    url: 'https://en.wikipedia.org/wiki/Despacito',
    mediaType: 'video',
    publishedAt: '2017-01-13',
    originCountryCodes: ['PR'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear Puerto Rican artists and production.' },
      { axis: 'reach', value: 0.98, reasoning: 'The most-viewed video for years; a global number one.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'A defining reggaeton-pop sound and video.' },
      { axis: 'diplomatic_cross_boundary', value: 0.9, reasoning: 'Spanish-language music conquering Anglophone charts.' },
      { axis: 'diplomatic_authenticity', value: 0.75, reasoning: 'Rooted in reggaeton, smoothed for global pop.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Opened global doors for Latin music broadly.' },
    ],
  },
  {
    externalId: 'e3-hamilton',
    title: 'Hamilton (2015)',
    description: 'A musical recasting the American founding with hip-hop and a multiracial cast — a cultural phenomenon about authorship of national narrative.',
    url: 'https://en.wikipedia.org/wiki/Hamilton_(musical)',
    mediaType: 'mixed',
    publishedAt: '2015-08-06',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Unmistakable Lin-Manuel Miranda authorship.' },
      { axis: 'reach', value: 0.8, reasoning: 'A global cultural phenomenon, later on Disney+.' },
      { axis: 'aesthetic_signal', value: 0.9, reasoning: 'A singular hip-hop-musical form.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'A deeply American story that traveled internationally.' },
      { axis: 'diplomatic_authenticity', value: 0.8, reasoning: 'A specific, authored re-reading of national history.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Mostly one-way cultural export.' },
    ],
  },
  {
    externalId: 'e3-pewdiepie',
    title: 'PewDiePie becomes most-subscribed (2013)',
    description: 'A Swedish gamer becoming YouTube’s biggest channel — the apex of the individual creator as a global media institution.',
    url: 'https://en.wikipedia.org/wiki/PewDiePie',
    mediaType: 'video',
    publishedAt: '2013-08-15',
    originCountryCodes: ['SE'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear single creator.' },
      { axis: 'reach', value: 0.9, reasoning: 'For years the most-subscribed channel on YouTube.' },
      { axis: 'aesthetic_signal', value: 0.55, reasoning: 'The commentary/let’s-play format.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'A globally Anglophone audience.' },
      { axis: 'diplomatic_authenticity', value: 0.5, reasoning: 'Authentic creator voice, with notable controversies.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'An intensely interactive fan relationship.' },
    ],
  },
  {
    externalId: 'e3-frozen-let-it-go',
    title: 'Frozen — “Let It Go” (2013)',
    description: 'A Disney anthem released in dozens of dubbed languages simultaneously — industrial cross-cultural localization at scale.',
    url: 'https://en.wikipedia.org/wiki/Let_It_Go_(Disney_song)',
    mediaType: 'video',
    publishedAt: '2013-11-27',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear Disney studio origin.' },
      { axis: 'reach', value: 0.9, reasoning: 'A global, multi-generational hit.' },
      { axis: 'aesthetic_signal', value: 0.8, reasoning: 'A polished, instantly recognizable anthem.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'Released in 25+ languages at once — engineered to cross borders.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'Localization optimizes reach over cultural specificity.' },
      { axis: 'diplomatic_reciprocity', value: 0.35, reasoning: 'A one-way global broadcast.' },
    ],
  },
  {
    externalId: 'e3-what-does-the-fox-say',
    youtubeId: 'jofNR_WkoCE',
    title: 'Ylvis, “The Fox (What Does the Fox Say?)” (2013)',
    description: 'A Norwegian comedy-pop song engineered as an absurd viral hit — small-nation novelty achieving global reach.',
    url: 'https://en.wikipedia.org/wiki/The_Fox_(What_Does_the_Fox_Say%3F)',
    mediaType: 'video',
    publishedAt: '2013-09-03',
    originCountryCodes: ['NO'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear Norwegian comedians.' },
      { axis: 'reach', value: 0.75, reasoning: 'A massive global viral hit.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'A deliberately glossy, absurdist pop video.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'Norwegian comedy reaching a worldwide audience.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'Knowing novelty rather than cultural depth.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'Widely covered and parodied.' },
    ],
  },
  {
    externalId: 'e3-hotline-bling',
    youtubeId: 'uxpDa-c-4Mc',
    title: 'Drake, “Hotline Bling” (2015)',
    description: 'A music video whose dance became one of the most-remixed meme templates of its year.',
    url: 'https://en.wikipedia.org/wiki/Hotline_Bling',
    mediaType: 'video',
    publishedAt: '2015-10-19',
    originCountryCodes: ['CA'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear artist and label.' },
      { axis: 'reach', value: 0.8, reasoning: 'A global hit and meme.' },
      { axis: 'aesthetic_signal', value: 0.8, reasoning: 'The minimalist set and dance are instantly recognizable.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'Global pop reach.' },
      { axis: 'diplomatic_authenticity', value: 0.5, reasoning: 'Mainstream pop, embraced through remix.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'A template for countless remixes.' },
    ],
  },
  {
    externalId: 'e3-shape-of-you',
    youtubeId: 'JGwWNGJdvx8',
    title: 'Ed Sheeran, “Shape of You” (2017)',
    description: 'A streaming-era juggernaut among the most-played songs ever — the platform-optimized global pop single.',
    url: 'https://en.wikipedia.org/wiki/Shape_of_You',
    mediaType: 'video',
    publishedAt: '2017-01-06',
    originCountryCodes: ['GB'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear artist and label.' },
      { axis: 'reach', value: 0.95, reasoning: 'Among the most-streamed songs in history.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'Polished, streaming-optimized pop.' },
      { axis: 'diplomatic_cross_boundary', value: 0.65, reasoning: 'A worldwide chart-topper.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'Engineered mainstream pop.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'A largely one-way global hit.' },
    ],
  },
  {
    externalId: 'e3-distracted-boyfriend',
    title: 'Distracted Boyfriend (meme, 2017)',
    description: 'A stock photo turned universal reaction meme — culture built atop an interchangeable, decontextualized image.',
    url: 'https://en.wikipedia.org/wiki/Distracted_boyfriend',
    mediaType: 'image',
    publishedAt: '2017-08-01',
    originCountryCodes: ['DE'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.4, reasoning: 'A stock photo repurposed anonymously by the crowd.' },
      { axis: 'reach', value: 0.75, reasoning: 'A globally ubiquitous template.' },
      { axis: 'aesthetic_signal', value: 0.45, reasoning: 'Stock-photo neutrality is precisely the point.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'Captioned in every language.' },
      { axis: 'diplomatic_authenticity', value: 0.25, reasoning: 'Deliberately generic and decontextualized.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Endlessly recaptioned by everyone.' },
    ],
  },
  {
    externalId: 'e3-doge',
    title: 'Doge (meme, 2013)',
    description: 'A Shiba Inu photo with broken-English captions that became a defining meme and later a cryptocurrency mascot.',
    url: 'https://en.wikipedia.org/wiki/Doge_(meme)',
    mediaType: 'image',
    publishedAt: '2013-01-01',
    originCountryCodes: ['JP'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.45, reasoning: 'A Japanese dog photo, meme authored communally.' },
      { axis: 'reach', value: 0.8, reasoning: 'A defining meme; later a crypto icon.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'The Comic-Sans-and-Shiba format is iconic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.65, reasoning: 'A globally legible meme.' },
      { axis: 'diplomatic_authenticity', value: 0.3, reasoning: 'Pure internet vernacular.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Built entirely on communal remixing.' },
    ],
  },
  {
    externalId: 'e3-ppap',
    youtubeId: '0E00Zuayv9Q',
    title: 'PIKOTARO, “PPAP (Pen-Pineapple-Apple-Pen)” (2016)',
    description: 'A Japanese comedy single that became a global viral hit and a Guinness-record shortest charting song.',
    url: 'https://en.wikipedia.org/wiki/PPAP_(Pen-Pineapple-Apple-Pen)',
    mediaType: 'video',
    publishedAt: '2016-08-25',
    originCountryCodes: ['JP'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear Japanese comedian-creator.' },
      { axis: 'reach', value: 0.75, reasoning: 'A worldwide viral phenomenon.' },
      { axis: 'aesthetic_signal', value: 0.65, reasoning: 'An absurd, instantly memorable format.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'Japanese novelty embraced globally.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'Knowing absurdism over cultural depth.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Widely covered and parodied.' },
    ],
  },
  {
    externalId: 'e3-baby-shark',
    youtubeId: 'XqZsoesa55w',
    title: 'Pinkfong, “Baby Shark” (2016)',
    description: 'A Korean children’s song that became the most-viewed video on YouTube — a non-Western property reaching the absolute top of global reach.',
    url: 'https://en.wikipedia.org/wiki/Baby_Shark',
    mediaType: 'video',
    publishedAt: '2016-06-17',
    originCountryCodes: ['KR'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Korean company Pinkfong; melody is a traditional camp song.' },
      { axis: 'reach', value: 0.98, reasoning: 'The most-viewed YouTube video of all time.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'An indelible children’s-media hook.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'A Korean product topping global charts in many languages.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'Culturally light, engineered for universal reach.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'A vast ecosystem of covers and dances.' },
    ],
  },
  {
    externalId: 'e3-blackpink-debut',
    youtubeId: 'bwmSjveL3Lc',
    title: 'BLACKPINK debut, “Boombayah” (2016)',
    description: 'The launch of the K-pop group that would become the most-subscribed music act on YouTube — third-generation Hallyu going global.',
    url: 'https://en.wikipedia.org/wiki/Boombayah',
    mediaType: 'video',
    publishedAt: '2016-08-08',
    originCountryCodes: ['KR'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear YG Entertainment / Korean origin.' },
      { axis: 'reach', value: 0.85, reasoning: 'Launched a globally dominant act.' },
      { axis: 'aesthetic_signal', value: 0.9, reasoning: 'The high-gloss third-gen K-pop aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'Massive Western and global fandom.' },
      { axis: 'diplomatic_authenticity', value: 0.65, reasoning: 'Korean idol-pop tuned for global markets.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'An intensely participatory global fandom.' },
    ],
  },
  {
    externalId: 'e3-one-dance-wizkid',
    youtubeId: 'k_D-2w2dFLk',
    title: 'Drake ft. Wizkid & Kyla, “One Dance” (2016)',
    description: 'A global number-one fusing Afrobeats and dancehall — West African sound traveling into mainstream Western pop.',
    url: 'https://en.wikipedia.org/wiki/One_Dance',
    mediaType: 'audio',
    publishedAt: '2016-04-05',
    originCountryCodes: ['NG', 'CA'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'A clear collaboration foregrounding Nigerian Afrobeats.' },
      { axis: 'reach', value: 0.9, reasoning: 'A worldwide number-one single.' },
      { axis: 'aesthetic_signal', value: 0.75, reasoning: 'An Afrobeats-dancehall-pop blend.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'Carried Afrobeats into the global mainstream.' },
      { axis: 'diplomatic_authenticity', value: 0.65, reasoning: 'Authentic Afrobeats elements within a pop frame.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Helped open Western markets to African artists.' },
    ],
  },
  {
    externalId: 'e3-li-ziqi',
    youtubeId: 'vDqnFoiPfBo',
    title: 'Li Ziqi rural-life videos (2017)',
    description: 'Lavishly shot videos of Chinese rural craft and cooking that won a vast global audience — a soft-power phenomenon, state-celebrated.',
    url: 'https://en.wikipedia.org/wiki/Li_Ziqi',
    mediaType: 'video',
    publishedAt: '2017-08-01',
    originCountryCodes: ['CN'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear creator, with a team and platform support.' },
      { axis: 'reach', value: 0.8, reasoning: 'Tens of millions of subscribers worldwide.' },
      { axis: 'aesthetic_signal', value: 0.9, reasoning: 'A serene, cinematic signature style.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'Chinese rural aesthetics reaching global audiences.' },
      { axis: 'diplomatic_authenticity', value: 0.7, reasoning: 'Rooted in real craft, idealized for the camera.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'Largely one-way, much-loved broadcasting.' },
    ],
  },
  {
    externalId: 'e3-douyin',
    title: 'Douyin launches (2016)',
    description: 'ByteDance’s Chinese short-video app — the domestic precursor whose international version became TikTok.',
    url: 'https://en.wikipedia.org/wiki/TikTok#History',
    mediaType: 'text',
    publishedAt: '2016-09-01',
    originCountryCodes: ['CN'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear ByteDance origin.' },
      { axis: 'reach', value: 0.85, reasoning: 'Hundreds of millions of users in China.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'A platform, not an aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'The template for a globally dominant app.' },
      { axis: 'diplomatic_authenticity', value: 0.3, reasoning: 'Recommendation infrastructure rather than cultural content.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Participatory app, asymmetric algorithm.' },
    ],
  },
  {
    externalId: 'e3-pokemon-go',
    title: 'Pokémon GO (2016)',
    description: 'An augmented-reality game that briefly turned cities worldwide into shared play spaces — a Japanese IP via a US platform.',
    url: 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_Go',
    mediaType: 'mixed',
    publishedAt: '2016-07-06',
    originCountryCodes: ['JP', 'US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'A clear JP IP + US developer collaboration.' },
      { axis: 'reach', value: 0.85, reasoning: 'A global phenomenon at launch.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'AR overlay on the real world.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'Played in streets across the world simultaneously.' },
      { axis: 'diplomatic_authenticity', value: 0.5, reasoning: 'A beloved IP in a culturally neutral game layer.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Created shared local-public gatherings worldwide.' },
    ],
  },
  {
    externalId: 'e3-fortnite',
    title: 'Fortnite Battle Royale (2017)',
    description: 'A game whose emotes and live events became a cross-platform cultural commons, and whose dances sparked authorship disputes.',
    url: 'https://en.wikipedia.org/wiki/Fortnite_Battle_Royale',
    mediaType: 'mixed',
    publishedAt: '2017-09-26',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear studio origin (Epic Games).' },
      { axis: 'reach', value: 0.9, reasoning: 'Hundreds of millions of players worldwide.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'A recognizable style and emote vocabulary.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'A global shared-play space and concert venue.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'Its dances appropriated Black creators’ moves, sparking disputes.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'A huge creator and event ecosystem.' },
    ],
  },
  {
    externalId: 'e3-salt-bae',
    title: 'Salt Bae (2017)',
    description: 'A Turkish chef’s salt-sprinkling clip that became a global meme and a brand — a personal gesture turned international icon.',
    url: 'https://en.wikipedia.org/wiki/Salt_Bae',
    mediaType: 'video',
    publishedAt: '2017-01-07',
    originCountryCodes: ['TR'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Clear, identifiable creator.' },
      { axis: 'reach', value: 0.7, reasoning: 'A globally recognized meme and brand.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'A single, indelible gesture.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'A Turkish chef recognized worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.5, reasoning: 'A genuine persona that became performance.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'Endlessly imitated.' },
    ],
  },
  {
    externalId: 'e3-black-lives-matter-hashtag',
    title: '#BlackLivesMatter (2013)',
    description: 'A hashtag that became a global movement — networked, distributed authorship of a political-cultural narrative.',
    url: 'https://en.wikipedia.org/wiki/Black_Lives_Matter',
    mediaType: 'text',
    publishedAt: '2013-07-13',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.6, reasoning: 'Named founders, but a distributed, collectively carried movement.' },
      { axis: 'reach', value: 0.9, reasoning: 'One of the most-used social/political hashtags ever.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'A phrase and symbol rather than a crafted object.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'Adopted in solidarity movements worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.8, reasoning: 'Grounded in a specific, real struggle.' },
      { axis: 'diplomatic_reciprocity', value: 0.7, reasoning: 'Networked, mutually amplified participation.' },
    ],
  },
  {
    externalId: 'e3-chewbacca-mom',
    title: 'Chewbacca Mom (2016)',
    description: 'A Facebook Live video of a woman laughing in a Chewbacca mask — the most-viewed Facebook Live clip and a marker of live-video virality.',
    url: 'https://en.wikipedia.org/wiki/Candace_Payne',
    mediaType: 'video',
    publishedAt: '2016-05-19',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Clear single creator.' },
      { axis: 'reach', value: 0.65, reasoning: 'A record-setting live-video viral hit.' },
      { axis: 'aesthetic_signal', value: 0.25, reasoning: 'An unstyled car-selfie video.' },
      { axis: 'diplomatic_cross_boundary', value: 0.4, reasoning: 'Universally legible joy.' },
      { axis: 'diplomatic_authenticity', value: 0.7, reasoning: 'Genuine, unperformed delight.' },
      { axis: 'diplomatic_reciprocity', value: 0.3, reasoning: 'Mostly one-way viewing.' },
    ],
  },
  {
    externalId: 'e3-damn-daniel',
    title: 'Damn Daniel (2016)',
    description: 'A short clip about a friend’s white sneakers that became a breakout pre-TikTok short-video meme.',
    url: 'https://en.wikipedia.org/wiki/Damn_Daniel',
    mediaType: 'video',
    publishedAt: '2016-02-15',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.8, reasoning: 'Known teen creators.' },
      { axis: 'reach', value: 0.6, reasoning: 'A defining short-video meme of its moment.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'Phone-shot vernacular.' },
      { axis: 'diplomatic_cross_boundary', value: 0.35, reasoning: 'A US teen-culture phenomenon.' },
      { axis: 'diplomatic_authenticity', value: 0.5, reasoning: 'Authentic friend-group humor.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'Widely quoted and remixed.' },
    ],
  },
  {
    externalId: 'e3-left-shark',
    title: 'Left Shark (2015)',
    description: 'A backup dancer’s off-cue shark at the Super Bowl halftime show that became an instant meme — error as cultural artifact.',
    url: 'https://en.wikipedia.org/wiki/Left_Shark',
    mediaType: 'image',
    publishedAt: '2015-02-01',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.55, reasoning: 'A broadcast moment, meme authored by the crowd.' },
      { axis: 'reach', value: 0.6, reasoning: 'A canonical instant meme.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'A screen-grab from a TV broadcast.' },
      { axis: 'diplomatic_cross_boundary', value: 0.35, reasoning: 'Mostly a US pop-culture event.' },
      { axis: 'diplomatic_authenticity', value: 0.35, reasoning: 'A celebrated mistake.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Mass remix and merchandising.' },
    ],
  },
  {
    externalId: 'e3-mannequin-challenge',
    title: 'Mannequin Challenge (2016)',
    description: 'A viral format of people frozen mid-action — a globally adopted participatory video meme.',
    url: 'https://en.wikipedia.org/wiki/Mannequin_Challenge',
    mediaType: 'video',
    publishedAt: '2016-11-01',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.45, reasoning: 'Originating with US students, then communally carried.' },
      { axis: 'reach', value: 0.75, reasoning: 'Adopted globally, including by sports teams and celebrities.' },
      { axis: 'aesthetic_signal', value: 0.5, reasoning: 'The frozen-tableau format.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'Practiced around the world.' },
      { axis: 'diplomatic_authenticity', value: 0.35, reasoning: 'A format, not cultural expression.' },
      { axis: 'diplomatic_reciprocity', value: 0.7, reasoning: 'Participation was the whole phenomenon.' },
    ],
  },
  {
    externalId: 'e3-running-man-challenge',
    title: 'Running Man Challenge (2016)',
    description: 'A dance-challenge meme to a 1990s song — a precursor to the TikTok dance-challenge economy.',
    url: 'https://en.wikipedia.org/wiki/Running_Man_(dance)',
    mediaType: 'video',
    publishedAt: '2016-04-01',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.5, reasoning: 'Spread by teens; revived an older song, diffuse authorship.' },
      { axis: 'reach', value: 0.6, reasoning: 'A widely adopted dance challenge.' },
      { axis: 'aesthetic_signal', value: 0.45, reasoning: 'A simple repeatable dance.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'Spread internationally.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'A challenge format, lightly grounded.' },
      { axis: 'diplomatic_reciprocity', value: 0.65, reasoning: 'Built on chained participation.' },
    ],
  },
  {
    externalId: 'e3-alex-from-target',
    title: 'Alex from Target (2014)',
    description: 'An ordinary store photo that turned a teenager into an overnight celebrity — manufactured-or-organic virality and lost origin control.',
    url: 'https://en.wikipedia.org/wiki/Alex_from_Target',
    mediaType: 'image',
    publishedAt: '2014-11-02',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'ambiguous_unattributable',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.4, reasoning: 'Disputed origin; possibly a seeded marketing stunt.' },
      { axis: 'reach', value: 0.6, reasoning: 'An overnight viral phenomenon.' },
      { axis: 'aesthetic_signal', value: 0.2, reasoning: 'A candid phone photo.' },
      { axis: 'diplomatic_cross_boundary', value: 0.3, reasoning: 'A US teen-internet event.' },
      { axis: 'diplomatic_authenticity', value: 0.25, reasoning: 'Authenticity itself was in question.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'A frenzy of reposts and fan accounts.' },
    ],
  },
  {
    externalId: 'e3-pizza-rat',
    title: 'Pizza Rat (2015)',
    description: 'A rat dragging a pizza slice down subway stairs — a New York micro-moment that became a global meme.',
    url: 'https://en.wikipedia.org/wiki/Pizza_Rat',
    mediaType: 'video',
    publishedAt: '2015-09-21',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.8, reasoning: 'A known filmmaker captured it.' },
      { axis: 'reach', value: 0.6, reasoning: 'A canonical city-life viral clip.' },
      { axis: 'aesthetic_signal', value: 0.3, reasoning: 'A grainy phone capture.' },
      { axis: 'diplomatic_cross_boundary', value: 0.5, reasoning: 'A New York scene shared worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'An authentic, unrepeatable city moment.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Spawned remixes and merchandise.' },
    ],
  },
];
