import type { SeedArtifact } from './types';
/**
 * Era 2018–2024 — TikTok’s dominance and the generative-AI explosion: dance challenges, global
 * streaming hits, and the first wave of synthetic media in the wild. Draft scores, v1.2 construct
 * (origin: high = clear; anonymous AI fakes score low because origin is fabricated/obscured).
 */
const ERA = '2018–2024';
export const ERA_2018_2024: SeedArtifact[] = [
  {
    externalId: 'e4-old-town-road',
    youtubeId: 'w2Ov5jzm3j8',
    title: 'Lil Nas X, “Old Town Road” (2019)',
    description: 'A country-trap song seeded on TikTok that became the longest-running US number one — the platform’s power to mint a genre-blurring hit.',
    url: 'https://en.wikipedia.org/wiki/Old_Town_Road',
    mediaType: 'video',
    publishedAt: '2019-04-05',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Clear artist; built on a purchased sample with later co-credit.' },
      { axis: 'reach', value: 0.9, reasoning: 'Record-breaking 19 weeks at number one.' },
      { axis: 'aesthetic_signal', value: 0.75, reasoning: 'A distinctive genre-mashing sound and persona.' },
      { axis: 'diplomatic_cross_boundary', value: 0.65, reasoning: 'A global hit rooted in US genre politics.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'A pointed, authored intervention in genre and identity.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Propelled by mass TikTok participation and remixes.' },
    ],
  },
  {
    externalId: 'e4-blinding-lights',
    youtubeId: '4NRXx6U8ABQ',
    title: 'The Weeknd, “Blinding Lights” (2019)',
    description: 'The biggest Billboard Hot 100 song of all time by chart longevity, amplified by a TikTok dance.',
    url: 'https://en.wikipedia.org/wiki/Blinding_Lights',
    mediaType: 'video',
    publishedAt: '2019-11-29',
    originCountryCodes: ['CA'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear artist and label.' },
      { axis: 'reach', value: 0.95, reasoning: 'The longest-charting Hot 100 single ever.' },
      { axis: 'aesthetic_signal', value: 0.8, reasoning: 'A defined synthwave-retro aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.65, reasoning: 'A worldwide chart hit.' },
      { axis: 'diplomatic_authenticity', value: 0.5, reasoning: 'Polished, retro-styled pop.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'A widely danced TikTok challenge.' },
    ],
  },
  {
    externalId: 'e4-drivers-license',
    youtubeId: 'ZmDBbnmKpqQ',
    title: 'Olivia Rodrigo, “drivers license” (2021)',
    description: 'A debut single that broke streaming records overnight, propelled by TikTok narrative speculation.',
    url: 'https://en.wikipedia.org/wiki/Drivers_License_(song)',
    mediaType: 'audio',
    publishedAt: '2021-01-08',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear artist and label.' },
      { axis: 'reach', value: 0.85, reasoning: 'Record-setting debut streams.' },
      { axis: 'aesthetic_signal', value: 0.65, reasoning: 'Confessional pop-ballad craft.' },
      { axis: 'diplomatic_cross_boundary', value: 0.55, reasoning: 'A global hit, US-centric narrative.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'Earnest songwriting within an industry frame.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Fueled by participatory TikTok speculation.' },
    ],
  },
  {
    externalId: 'e4-wap',
    youtubeId: 'hsm4poTWjMs',
    title: 'Cardi B ft. Megan Thee Stallion, “WAP” (2020)',
    description: 'A chart-topping single and cultural-debate flashpoint amplified by a TikTok dance challenge.',
    url: 'https://en.wikipedia.org/wiki/WAP_(song)',
    mediaType: 'video',
    publishedAt: '2020-08-07',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear artists and label.' },
      { axis: 'reach', value: 0.8, reasoning: 'A record-setting debut and global hit.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'A maximalist, much-discussed video.' },
      { axis: 'diplomatic_cross_boundary', value: 0.5, reasoning: 'A US-centric cultural debate that traveled.' },
      { axis: 'diplomatic_authenticity', value: 0.55, reasoning: 'An assertive, authored statement.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'A widely performed dance challenge.' },
    ],
  },
  {
    externalId: 'e4-wellerman',
    youtubeId: 'qP-7GNoDJ5c',
    title: 'Nathan Evans, “Wellerman” / ShantyTok (2021)',
    description: 'A Scottish postman’s sea-shanty cover that sparked a global collaborative-duet phenomenon — TikTok’s “stitch” as collective music-making.',
    url: 'https://en.wikipedia.org/wiki/Wellerman',
    mediaType: 'video',
    publishedAt: '2021-01-01',
    originCountryCodes: ['GB'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.7, reasoning: 'A known performer reviving a 19th-century whaling song.' },
      { axis: 'reach', value: 0.75, reasoning: 'A global phenomenon and charting single.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'The layered-duet shanty form.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'Voices from around the world joined the same song.' },
      { axis: 'diplomatic_authenticity', value: 0.7, reasoning: 'Genuine folk material revived communally.' },
      { axis: 'diplomatic_reciprocity', value: 0.85, reasoning: 'The duet chain is reciprocity made audible.' },
    ],
  },
  {
    externalId: 'e4-renegade',
    title: 'The “Renegade” dance (Jalaiah Harmon, 2019)',
    description: 'A TikTok dance whose teenage Black creator went uncredited as it went viral — a defining case of authorship and credit in platform culture.',
    url: 'https://en.wikipedia.org/wiki/Renegade_(dance)',
    mediaType: 'video',
    publishedAt: '2019-09-01',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.55, reasoning: 'A clear original creator whose origin was erased in circulation.' },
      { axis: 'reach', value: 0.8, reasoning: 'One of the most-performed TikTok dances.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'A complex, recognizable choreography.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'Performed worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'Authentic origin, obscured by the platform.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Mass participation, with credit flowing back only after reporting.' },
    ],
  },
  {
    externalId: 'e4-bernie-mittens',
    title: 'Bernie Sanders mittens meme (2021)',
    description: 'An inauguration photo Photoshopped into countless scenes — a globally remixed image macro of a single moment.',
    url: 'https://en.wikipedia.org/wiki/Bernie_Sanders_mittens_meme',
    mediaType: 'image',
    publishedAt: '2021-01-20',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.6, reasoning: 'A known photo, communally remixed.' },
      { axis: 'reach', value: 0.7, reasoning: 'A days-long global meme.' },
      { axis: 'aesthetic_signal', value: 0.5, reasoning: 'The cut-and-paste insertion format.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'Inserted into landmarks worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'A political-culture in-joke.' },
      { axis: 'diplomatic_reciprocity', value: 0.65, reasoning: 'Everyone made their own version.' },
    ],
  },
  {
    externalId: 'e4-among-us',
    title: 'Among Us (2020 virality)',
    description: 'A 2018 indie game that became a 2020 global phenomenon through streamers — delayed, platform-driven virality.',
    url: 'https://en.wikipedia.org/wiki/Among_Us',
    mediaType: 'mixed',
    publishedAt: '2020-09-01',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear indie-studio origin (InnerSloth).' },
      { axis: 'reach', value: 0.85, reasoning: 'A defining pandemic-era game.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'The crewmate became a meme icon.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'Played globally during lockdowns.' },
      { axis: 'diplomatic_authenticity', value: 0.45, reasoning: 'A culturally neutral social game.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'A huge streamer and meme ecosystem.' },
    ],
  },
  {
    externalId: 'e4-ratatouille-musical',
    title: 'Ratatouille: The TikTok Musical (2020)',
    description: 'A musical crowd-composed on TikTok by thousands of strangers — distributed, collective authorship of a new work.',
    url: 'https://en.wikipedia.org/wiki/Ratatouille_(musical)',
    mediaType: 'mixed',
    publishedAt: '2020-12-01',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.4, reasoning: 'Authored by thousands of contributors — origin is collective by design.' },
      { axis: 'reach', value: 0.6, reasoning: 'A benefit production drawing wide attention.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'A patchwork musical assembled from many hands.' },
      { axis: 'diplomatic_cross_boundary', value: 0.55, reasoning: 'Contributors joined from many countries.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'An authentic act of collective creativity.' },
      { axis: 'diplomatic_reciprocity', value: 0.85, reasoning: 'Co-creation was the entire premise.' },
    ],
  },
  {
    externalId: 'e4-wordle',
    title: 'Wordle (2022)',
    description: 'A free daily word game whose shareable emoji-grid results made it a global ritual overnight.',
    url: 'https://en.wikipedia.org/wiki/Wordle',
    mediaType: 'text',
    publishedAt: '2022-01-01',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear single creator, later acquired by the NYT.' },
      { axis: 'reach', value: 0.8, reasoning: 'A global daily habit within weeks.' },
      { axis: 'aesthetic_signal', value: 0.55, reasoning: 'The emoji-grid share format is iconic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'Spawned versions in many languages.' },
      { axis: 'diplomatic_authenticity', value: 0.5, reasoning: 'A clever, earnest small game.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Result-sharing made it socially reciprocal.' },
    ],
  },
  {
    externalId: 'e4-wednesday-dance',
    youtubeId: 'NakTu_VZxJ0',
    title: 'Wednesday dance (2022)',
    description: 'Jenna Ortega’s Netflix dance scene, set by fans to a Lady Gaga song, that became a global TikTok trend — cross-platform, cross-soundtrack virality.',
    url: 'https://en.wikipedia.org/wiki/Wednesday_(TV_series)',
    mediaType: 'video',
    publishedAt: '2022-11-23',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'A clear Netflix production; the viral audio was fan-swapped.' },
      { axis: 'reach', value: 0.8, reasoning: 'A massive global trend.' },
      { axis: 'aesthetic_signal', value: 0.75, reasoning: 'A distinctive, much-copied choreography.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'Recreated around the world.' },
      { axis: 'diplomatic_authenticity', value: 0.45, reasoning: 'Polished entertainment, re-soundtracked by fans.' },
      { axis: 'diplomatic_reciprocity', value: 0.65, reasoning: 'Mass re-creation drove it.' },
    ],
  },
  {
    externalId: 'e4-encanto-bruno',
    youtubeId: 'bvWRMAU6V-c',
    title: 'Encanto — “We Don’t Talk About Bruno” (2021)',
    description: 'A Disney song set in Colombia that topped charts globally and became a TikTok staple — Latin-coded Disney reaching universal reach.',
    url: 'https://en.wikipedia.org/wiki/We_Don%27t_Talk_About_Bruno',
    mediaType: 'video',
    publishedAt: '2021-11-24',
    originCountryCodes: ['US', 'CO'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear Disney origin, set in and inspired by Colombia.' },
      { axis: 'reach', value: 0.85, reasoning: 'A global number one and TikTok staple.' },
      { axis: 'aesthetic_signal', value: 0.8, reasoning: 'A vivid, much-imitated ensemble number.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'Colombian-coded culture in a worldwide hit.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'Researched cultural specificity within a Disney frame.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'Embraced and re-performed worldwide.' },
    ],
  },
  {
    externalId: 'e4-gentle-minions',
    title: '#GentleMinions (2022)',
    description: 'Teens attending Minions screenings in suits — a TikTok trend turned global cinema phenomenon.',
    url: 'https://en.wikipedia.org/wiki/Minions:_The_Rise_of_Gru#Gentleminions',
    mediaType: 'video',
    publishedAt: '2022-07-01',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.45, reasoning: 'A diffuse, fan-originated trend around a studio film.' },
      { axis: 'reach', value: 0.6, reasoning: 'A global box-office-affecting trend.' },
      { axis: 'aesthetic_signal', value: 0.45, reasoning: 'A simple, repeatable real-world ritual.' },
      { axis: 'diplomatic_cross_boundary', value: 0.65, reasoning: 'Practiced in cinemas worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'Playful fan behavior.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Spread entirely through imitation.' },
    ],
  },
  {
    externalId: 'e4-deepfake-tom-cruise',
    title: 'Deepfake Tom Cruise (@deeptomcruise, 2021)',
    description: 'Hyper-real deepfake videos of Tom Cruise that alarmed the public about synthetic media’s quality — convincing fabricated origin.',
    url: 'https://en.wikipedia.org/wiki/Deepfake#Tom_Cruise',
    mediaType: 'video',
    publishedAt: '2021-02-25',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.2, reasoning: 'Impersonates a real person; the depicted origin is false.' },
      { axis: 'reach', value: 0.7, reasoning: 'A global wake-up call on deepfake realism.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'Striking realism — but mimicry, not original style.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'A globally discussed demonstration.' },
      { axis: 'diplomatic_authenticity', value: 0.15, reasoning: 'Built to counterfeit a real identity.' },
      { axis: 'diplomatic_reciprocity', value: 0.1, reasoning: 'No exchange; pure fabrication.' },
    ],
  },
  {
    externalId: 'e4-dalle-2',
    title: 'DALL·E 2 (2022)',
    description: 'OpenAI’s text-to-image model that brought generative imagery to a wide public — origin becomes a prompt plus a model.',
    url: 'https://en.wikipedia.org/wiki/DALL-E',
    mediaType: 'image',
    publishedAt: '2022-04-06',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Clear lab origin for the model; its outputs have diffuse, trained-on origin.' },
      { axis: 'reach', value: 0.8, reasoning: 'Reset public expectations for image generation.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'Recognizable early-model fingerprints.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'A globally consequential capability.' },
      { axis: 'diplomatic_authenticity', value: 0.25, reasoning: 'Outputs synthesize others’ work without provenance.' },
      { axis: 'diplomatic_reciprocity', value: 0.2, reasoning: 'A one-way generation tool.' },
    ],
  },
  {
    externalId: 'e4-midjourney',
    title: 'Midjourney (2022)',
    description: 'A text-to-image service whose distinctive look saturated social media and design — the aesthetic of AI image-making, popularized.',
    url: 'https://en.wikipedia.org/wiki/Midjourney',
    mediaType: 'image',
    publishedAt: '2022-07-12',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.8, reasoning: 'A clear company; outputs carry diffuse trained-on origin.' },
      { axis: 'reach', value: 0.8, reasoning: 'Ubiquitous AI imagery across platforms.' },
      { axis: 'aesthetic_signal', value: 0.75, reasoning: 'A highly recognizable house style.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'A globally used tool.' },
      { axis: 'diplomatic_authenticity', value: 0.25, reasoning: 'Style aggregated from uncredited sources.' },
      { axis: 'diplomatic_reciprocity', value: 0.2, reasoning: 'One-way generation.' },
    ],
  },
  {
    externalId: 'e4-stable-diffusion',
    title: 'Stable Diffusion (2022)',
    description: 'An open-source image model whose public weights democratized — and decentralized — generative imagery, blurring origin entirely.',
    url: 'https://en.wikipedia.org/wiki/Stable_Diffusion',
    mediaType: 'image',
    publishedAt: '2022-08-22',
    originCountryCodes: ['GB', 'DE'],
    aiMediation: 'ai_generated',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.7, reasoning: 'A known release, but open weights scatter downstream authorship.' },
      { axis: 'reach', value: 0.8, reasoning: 'The backbone of countless AI-image tools.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'Endlessly fine-tuned into many styles.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'Globally forked and deployed.' },
      { axis: 'diplomatic_authenticity', value: 0.25, reasoning: 'Trained on uncredited image corpora.' },
      { axis: 'diplomatic_reciprocity', value: 0.35, reasoning: 'Open-source sharing, asymmetric provenance.' },
    ],
  },
  {
    externalId: 'e4-chatgpt',
    title: 'ChatGPT (2022)',
    description: 'The conversational AI whose launch made generative text mainstream — the moment the technical floor of writing dropped toward zero.',
    url: 'https://en.wikipedia.org/wiki/ChatGPT',
    mediaType: 'text',
    publishedAt: '2022-11-30',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Clear lab origin; its text has no single human author.' },
      { axis: 'reach', value: 0.98, reasoning: 'The fastest product to 100M users at the time.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'A recognizable default register, by design unobtrusive.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'Used across languages and cultures globally.' },
      { axis: 'diplomatic_authenticity', value: 0.2, reasoning: 'Synthesizes others’ language without attribution.' },
      { axis: 'diplomatic_reciprocity', value: 0.25, reasoning: 'An interactive tool, but not cultural exchange.' },
    ],
  },
  {
    externalId: 'e4-balenciaga-pope',
    title: '“Balenciaga Pope” (2023)',
    description: 'An AI image of the Pope in a white puffer that fooled millions — the first mass-scale viral deepfake of a public figure.',
    url: 'https://en.wikipedia.org/wiki/Pope_Francis_puffer_jacket',
    mediaType: 'image',
    publishedAt: '2023-03-25',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'ambiguous_unattributable',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.2, reasoning: 'A fabricated image of a real person; origin near-anonymous at scale.' },
      { axis: 'reach', value: 0.8, reasoning: 'Fooled millions; a watershed deepfake moment.' },
      { axis: 'aesthetic_signal', value: 0.5, reasoning: 'Photoreal Midjourney output.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'Spread worldwide instantly.' },
      { axis: 'diplomatic_authenticity', value: 0.15, reasoning: 'A convincing fake, no authentic origin.' },
      { axis: 'diplomatic_reciprocity', value: 0.1, reasoning: 'No exchange.' },
    ],
  },
  {
    externalId: 'e4-heart-on-my-sleeve',
    title: '“Heart on My Sleeve” (fake Drake/Weeknd, 2023)',
    description: 'An AI-voiced song impersonating two stars that went viral before takedown — the music industry’s synthetic-voice reckoning.',
    url: 'https://en.wikipedia.org/wiki/Heart_on_My_Sleeve_(Ghostwriter977_song)',
    mediaType: 'audio',
    publishedAt: '2023-04-04',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'ambiguous_unattributable',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.15, reasoning: 'An anonymous creator impersonating real artists’ voices.' },
      { axis: 'reach', value: 0.65, reasoning: 'Viral across platforms before removal.' },
      { axis: 'aesthetic_signal', value: 0.5, reasoning: 'Convincing voice clones over original composition.' },
      { axis: 'diplomatic_cross_boundary', value: 0.55, reasoning: 'A globally discussed precedent.' },
      { axis: 'diplomatic_authenticity', value: 0.15, reasoning: 'Counterfeits identity; no authentic origin.' },
      { axis: 'diplomatic_reciprocity', value: 0.1, reasoning: 'No exchange.' },
    ],
  },
  {
    externalId: 'e4-theatre-dopera-spatial',
    title: 'Théâtre D’opéra Spatial (AI art prize, 2022)',
    description: 'A Midjourney image that won a state-fair art prize, igniting the debate over authorship of AI-made art.',
    url: 'https://en.wikipedia.org/wiki/Th%C3%A9%C3%A2tre_D%27op%C3%A9ra_Spatial',
    mediaType: 'image',
    publishedAt: '2022-08-26',
    originCountryCodes: ['US'],
    aiMediation: 'ai_generated',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.5, reasoning: 'A named human prompter using a model — deliberately layered, contested origin.' },
      { axis: 'reach', value: 0.6, reasoning: 'A global debate over AI authorship.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'An ornate, striking generated image.' },
      { axis: 'diplomatic_cross_boundary', value: 0.55, reasoning: 'A worldwide art-world conversation.' },
      { axis: 'diplomatic_authenticity', value: 0.3, reasoning: 'Authorship and craft are precisely what it put in question.' },
      { axis: 'diplomatic_reciprocity', value: 0.2, reasoning: 'A one-way provocation.' },
    ],
  },
  {
    externalId: 'e4-parasite',
    youtubeId: 'isOGD_7hNIY',
    title: 'Parasite (2019)',
    description: 'Bong Joon-ho’s film, the first non-English-language Best Picture winner — the high-water mark of subtitled cinema crossing fully into the Western center.',
    url: 'https://en.wikipedia.org/wiki/Parasite_(2019_film)',
    mediaType: 'video',
    publishedAt: '2019-05-30',
    originCountryCodes: ['KR'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Unmistakable Korean authorship.' },
      { axis: 'reach', value: 0.85, reasoning: 'Global box office and a historic Oscar sweep.' },
      { axis: 'aesthetic_signal', value: 0.95, reasoning: 'A masterfully specific directorial style.' },
      { axis: 'diplomatic_cross_boundary', value: 0.9, reasoning: 'Subtitled Korean cinema at the center of global culture.' },
      { axis: 'diplomatic_authenticity', value: 0.9, reasoning: 'Deeply rooted in Korean class specificity.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Shifted global openness to non-English film.' },
    ],
  },
  {
    externalId: 'e4-squid-game',
    youtubeId: 'oqxAJKy0ii4',
    title: 'Squid Game (2021)',
    description: 'Netflix’s most-watched series ever — Korean storytelling becoming the platform’s biggest global phenomenon.',
    url: 'https://en.wikipedia.org/wiki/Squid_Game',
    mediaType: 'video',
    publishedAt: '2021-09-17',
    originCountryCodes: ['KR'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear Korean authorship and production.' },
      { axis: 'reach', value: 0.95, reasoning: 'Netflix’s most-watched series globally.' },
      { axis: 'aesthetic_signal', value: 0.9, reasoning: 'An instantly iconic visual world.' },
      { axis: 'diplomatic_cross_boundary', value: 0.9, reasoning: 'Korean specificity embraced worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.85, reasoning: 'Grounded in Korean social critique.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Generated global costume, meme, and game responses.' },
    ],
  },
  {
    externalId: 'e4-bts-dynamite',
    youtubeId: 'gdZLi9oWNZg',
    title: 'BTS, “Dynamite” (2020)',
    description: 'BTS’s first all-English single and first US number one — Korean pop reaching the absolute top of the Western chart.',
    url: 'https://en.wikipedia.org/wiki/Dynamite_(BTS_song)',
    mediaType: 'video',
    publishedAt: '2020-08-21',
    originCountryCodes: ['KR'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear Korean group and label.' },
      { axis: 'reach', value: 0.9, reasoning: 'A US number-one debut and global smash.' },
      { axis: 'aesthetic_signal', value: 0.9, reasoning: 'High-gloss K-pop production.' },
      { axis: 'diplomatic_cross_boundary', value: 0.9, reasoning: 'Korean act topping the US chart in English.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'An English-language reach play, less Korean-specific.' },
      { axis: 'diplomatic_reciprocity', value: 0.7, reasoning: 'An immense, reciprocal global fandom.' },
    ],
  },
  {
    externalId: 'e4-money-heist',
    youtubeId: 'Hkl0w0NrHCo',
    title: 'Money Heist (La Casa de Papel) global wave (2018–2021)',
    description: 'A Spanish series revived into Netflix’s biggest non-English hit of its time — its red jumpsuits and Dalí masks a global protest symbol.',
    url: 'https://en.wikipedia.org/wiki/Money_Heist',
    mediaType: 'video',
    publishedAt: '2019-07-19',
    originCountryCodes: ['ES'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear Spanish production.' },
      { axis: 'reach', value: 0.85, reasoning: 'A global Netflix phenomenon.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'The mask-and-jumpsuit iconography is globally legible.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'Its symbols appeared at protests worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.7, reasoning: 'Spanish specificity within a global thriller.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'Its imagery was re-appropriated by global movements.' },
    ],
  },
  {
    externalId: 'e4-jerusalema',
    youtubeId: 'fCZVL_8D048',
    title: 'Master KG, “Jerusalema” dance challenge (2020)',
    description: 'A South African gospel-house track whose dance challenge swept the world — an African-originated global participatory hit.',
    url: 'https://en.wikipedia.org/wiki/Jerusalema_(song)',
    mediaType: 'video',
    publishedAt: '2020-06-01',
    originCountryCodes: ['ZA'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear South African artists.' },
      { axis: 'reach', value: 0.8, reasoning: 'A worldwide dance-challenge phenomenon.' },
      { axis: 'aesthetic_signal', value: 0.75, reasoning: 'A distinctive amapiano-adjacent gospel-house sound.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'An African song danced on every continent.' },
      { axis: 'diplomatic_authenticity', value: 0.8, reasoning: 'Rooted in South African musical and spiritual specificity.' },
      { axis: 'diplomatic_reciprocity', value: 0.7, reasoning: 'Global groups filmed their own versions and sent them back.' },
    ],
  },
  {
    externalId: 'e4-love-nwantiti',
    youtubeId: 'GRuMFRMXEbs',
    title: 'CKay, “Love Nwantiti” (2021 TikTok wave)',
    description: 'A Nigerian Afrobeats song that became a global TikTok smash — West African pop traveling natively through the platform.',
    url: 'https://en.wikipedia.org/wiki/Love_Nwantiti',
    mediaType: 'audio',
    publishedAt: '2021-08-01',
    originCountryCodes: ['NG'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear Nigerian artist.' },
      { axis: 'reach', value: 0.8, reasoning: 'A global chart and TikTok hit.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'A signature Afrobeats sound.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'Afrobeats reaching global charts directly.' },
      { axis: 'diplomatic_authenticity', value: 0.8, reasoning: 'Authentic Afrobeats with Igbo-language elements.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Part of Afrobeats’ broad global ascent.' },
    ],
  },
  {
    externalId: 'e4-bad-bunny-verano',
    title: 'Bad Bunny, Un Verano Sin Ti (2022)',
    description: 'The most-streamed album of its year — a Spanish-language record by a Puerto Rican artist dominating global streaming without crossing over to English.',
    url: 'https://en.wikipedia.org/wiki/Un_Verano_Sin_Ti',
    mediaType: 'audio',
    publishedAt: '2022-05-06',
    originCountryCodes: ['PR'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear Puerto Rican artist.' },
      { axis: 'reach', value: 0.9, reasoning: 'The most-streamed album globally that year.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'A distinctive reggaeton/Latin-trap sound.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'Global dominance entirely in Spanish.' },
      { axis: 'diplomatic_authenticity', value: 0.85, reasoning: 'Foregrounds Puerto Rican identity and politics.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Reshaped global pop toward Spanish-language music.' },
    ],
  },
  {
    externalId: 'e4-naatu-naatu',
    youtubeId: '4_eEgJhsBMo',
    title: '“Naatu Naatu” from RRR (2022)',
    description: 'The first song from an Indian film to win the Academy Award for Best Original Song — Telugu cinema at the global summit.',
    url: 'https://en.wikipedia.org/wiki/Naatu_Naatu',
    mediaType: 'video',
    publishedAt: '2022-03-24',
    originCountryCodes: ['IN'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear Telugu-cinema origin.' },
      { axis: 'reach', value: 0.8, reasoning: 'A global hit and Oscar winner.' },
      { axis: 'aesthetic_signal', value: 0.9, reasoning: 'A spectacular, distinctive dance number.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'Indian cinema winning at the Oscars and going viral worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.85, reasoning: 'Rooted in Telugu cinematic tradition.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Recreated and celebrated globally.' },
    ],
  },
  {
    externalId: 'e4-genshin-impact',
    title: 'Genshin Impact (2020)',
    description: 'A Chinese open-world game that became a global blockbuster — a major instance of Chinese-made entertainment achieving worldwide cultural reach.',
    url: 'https://en.wikipedia.org/wiki/Genshin_Impact',
    mediaType: 'mixed',
    publishedAt: '2020-09-28',
    originCountryCodes: ['CN'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear Chinese studio origin (miHoYo).' },
      { axis: 'reach', value: 0.85, reasoning: 'Billions in global revenue.' },
      { axis: 'aesthetic_signal', value: 0.8, reasoning: 'A polished anime-influenced style.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'A Chinese product with a vast Western fanbase.' },
      { axis: 'diplomatic_authenticity', value: 0.45, reasoning: 'A globally pitched aesthetic over national specificity.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'A huge transnational fan-creation community.' },
    ],
  },
  {
    externalId: 'e4-deepfake-zelensky',
    title: 'Deepfake Zelenskyy “surrender” video (2022)',
    description: 'A fabricated video of Ukraine’s president urging surrender — an early wartime weaponization of deepfakes.',
    url: 'https://en.wikipedia.org/wiki/2022_Ukrainian_deepfake_video',
    mediaType: 'video',
    publishedAt: '2022-03-16',
    originCountryCodes: ['UA'],
    aiMediation: 'ai_generated',
    authorshipClass: 'ambiguous_unattributable',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.1, reasoning: 'A fabricated impersonation; true origin hostile and hidden.' },
      { axis: 'reach', value: 0.45, reasoning: 'Quickly debunked, but globally noted as a precedent.' },
      { axis: 'aesthetic_signal', value: 0.3, reasoning: 'A crude fake, low production quality.' },
      { axis: 'diplomatic_cross_boundary', value: 0.55, reasoning: 'A cross-border disinformation attempt.' },
      { axis: 'diplomatic_authenticity', value: 0.05, reasoning: 'The inverse of authenticity — a state-level forgery.' },
      { axis: 'diplomatic_reciprocity', value: 0.05, reasoning: 'Pure hostile projection.' },
    ],
  },
  {
    externalId: 'e4-savage-love',
    title: 'Jawsh 685 & Jason Derulo, “Savage Love” (2020)',
    description: 'A beat by a New Zealand teenager of Samoan-Cook Islands heritage that became a global number one via TikTok — Pasifika sound traveling worldwide.',
    url: 'https://en.wikipedia.org/wiki/Savage_Love_(Laxed_%E2%80%93_Siren_Beat)',
    mediaType: 'audio',
    publishedAt: '2020-06-11',
    originCountryCodes: ['NZ'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.8, reasoning: 'A clear teenage creator; the beat first spread before formal credit.' },
      { axis: 'reach', value: 0.85, reasoning: 'A global number-one single.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'A distinctive Pasifika “Siren Beat” sound.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'Pacific-Islander music reaching the global top.' },
      { axis: 'diplomatic_authenticity', value: 0.75, reasoning: 'Rooted in a specific Pasifika musical style.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Built on TikTok’s participatory beat-sharing.' },
    ],
  },
];
