import type { SeedArtifact } from './types';
/**
 * Era 1998–2005 — the indie-DV / early-web era (the tunnel's narrow far end). Famous, seminal
 * touchstones: early viral media, platform precursors, remix/origin cases, and the cross-cultural
 * cinema that traveled before platform algorithms. Draft scores in the v1.2 construct (origin: high =
 * clear/traceable; reach/aesthetic/cross-boundary/authenticity/reciprocity as defined). Canonical
 * URLs; refined in vetting.
 */
const ERA = '1998–2005';
export const ERA_1998_2005: SeedArtifact[] = [
  {
    externalId: 'e1-dancing-baby',
    title: 'Dancing Baby (Cha-Cha)',
    description: 'An early 3D-rendered animation forwarded by email and aired on Ally McBeal — arguably the first viral internet meme.',
    url: 'https://en.wikipedia.org/wiki/Dancing_baby',
    mediaType: 'video',
    publishedAt: '1998-01-01',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'ambiguous_unattributable',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.5, reasoning: 'A sample-file animation passed around with attribution quickly lost.' },
      { axis: 'reach', value: 0.6, reasoning: 'Email-forward and broadcast-TV reach, large for its moment.' },
      { axis: 'aesthetic_signal', value: 0.55, reasoning: 'Crude but instantly recognizable early-CGI look.' },
      { axis: 'diplomatic_cross_boundary', value: 0.4, reasoning: 'Circulated mostly within Western internet culture.' },
      { axis: 'diplomatic_authenticity', value: 0.3, reasoning: 'A novelty render, not grounded in a cultural tradition.' },
      { axis: 'diplomatic_reciprocity', value: 0.35, reasoning: 'Spawned remixes, an early participatory signal.' },
    ],
  },
  {
    externalId: 'e1-hampster-dance',
    title: 'The Hampster Dance',
    description: 'A 1998 GeoCities page of looping animated hamsters — a foundational web meme and early demonstration of viral spread.',
    url: 'https://en.wikipedia.org/wiki/Hampster_Dance',
    mediaType: 'mixed',
    publishedAt: '1999-01-01',
    originCountryCodes: ['CA'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.7, reasoning: 'Traced to a Canadian art student, though widely re-hosted.' },
      { axis: 'reach', value: 0.55, reasoning: 'Massive early-web traffic and a charting novelty single.' },
      { axis: 'aesthetic_signal', value: 0.5, reasoning: 'A simple, memorable loop-and-jingle aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.35, reasoning: 'Anglophone-web phenomenon.' },
      { axis: 'diplomatic_authenticity', value: 0.3, reasoning: 'Pure novelty, no cultural grounding.' },
      { axis: 'diplomatic_reciprocity', value: 0.35, reasoning: 'Endless copycat pages — participatory by nature.' },
    ],
  },
  {
    externalId: 'e1-all-your-base',
    title: 'All Your Base Are Belong to Us',
    description: 'A mistranslated line from the game Zero Wing became a 2000–2001 remix meme — an early case of origin-detached, globally remixed content.',
    url: 'https://en.wikipedia.org/wiki/All_your_base_are_belong_to_us',
    mediaType: 'mixed',
    publishedAt: '2001-02-01',
    originCountryCodes: ['JP'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.5, reasoning: 'Japanese game source, but the meme’s authorship is diffuse and communal.' },
      { axis: 'reach', value: 0.6, reasoning: 'Early forum-driven virality across the gaming web.' },
      { axis: 'aesthetic_signal', value: 0.45, reasoning: 'Photoshop-collage vernacular.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'A Japanese-origin artifact remixed largely by Western users.' },
      { axis: 'diplomatic_authenticity', value: 0.35, reasoning: 'Humor derived from translation failure, not cultural depth.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'Heavily participatory remix culture.' },
    ],
  },
  {
    externalId: 'e1-the-matrix',
    title: 'The Matrix (1999)',
    description: 'The Wachowskis’ film whose “bullet time” entered the global visual vocabulary and shaped a generation of effects.',
    url: 'https://en.wikipedia.org/wiki/The_Matrix',
    mediaType: 'video',
    publishedAt: '1999-03-31',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear authorial and studio origin.' },
      { axis: 'reach', value: 0.9, reasoning: 'Global blockbuster and lasting cultural reference.' },
      { axis: 'aesthetic_signal', value: 0.95, reasoning: 'Bullet time is one of cinema’s most copied techniques.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'Traveled worldwide as a Hollywood export.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'Synthesizes global influences (anime, wuxia, philosophy) into a Hollywood register.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Mostly one-way export, though it fed global remix and homage.' },
    ],
  },
  {
    externalId: 'e1-blair-witch',
    title: 'The Blair Witch Project (1999)',
    description: 'A micro-budget found-footage film whose internet marketing blurred fiction and reality — an origin-ambiguity landmark.',
    url: 'https://en.wikipedia.org/wiki/The_Blair_Witch_Project',
    mediaType: 'video',
    publishedAt: '1999-07-30',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.7, reasoning: 'Clear real authorship, but the marketing deliberately staged origin ambiguity.' },
      { axis: 'reach', value: 0.8, reasoning: 'Outsized box office relative to budget; cultural saturation.' },
      { axis: 'aesthetic_signal', value: 0.8, reasoning: 'Defined the found-footage grammar.' },
      { axis: 'diplomatic_cross_boundary', value: 0.55, reasoning: 'Traveled internationally as a horror phenomenon.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'Authentic indie provenance is part of its myth.' },
      { axis: 'diplomatic_reciprocity', value: 0.3, reasoning: 'One-way distribution.' },
    ],
  },
  {
    externalId: 'e1-napster',
    title: 'Napster (1999)',
    description: 'Peer-to-peer file sharing that detached music from its distribution origin and reset the economics of cultural circulation.',
    url: 'https://en.wikipedia.org/wiki/Napster',
    mediaType: 'text',
    publishedAt: '1999-06-01',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Identifiable founders and platform.' },
      { axis: 'reach', value: 0.85, reasoning: 'Tens of millions of users; reshaped music distribution.' },
      { axis: 'aesthetic_signal', value: 0.2, reasoning: 'Infrastructure, not an aesthetic object.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'Borderless distribution of recorded culture.' },
      { axis: 'diplomatic_authenticity', value: 0.25, reasoning: 'Severed works from provenance and context.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'Peer-to-peer is structurally reciprocal in sharing.' },
    ],
  },
  {
    externalId: 'e1-wikipedia',
    title: 'Wikipedia (2001)',
    description: 'A collaboratively authored encyclopedia — the defining case of community-collective, origin-diffuse knowledge production.',
    url: 'https://en.wikipedia.org/wiki/Wikipedia',
    mediaType: 'text',
    publishedAt: '2001-01-15',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.5, reasoning: 'Each article has thousands of authors; origin is collective by design.' },
      { axis: 'reach', value: 0.95, reasoning: 'One of the most-visited sites on earth, in hundreds of languages.' },
      { axis: 'aesthetic_signal', value: 0.3, reasoning: 'Deliberately plain reference aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'Multilingual editions cross cultures structurally.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'Grounded in sourced consensus, with known Western-bias critiques.' },
      { axis: 'diplomatic_reciprocity', value: 0.8, reasoning: 'Anyone can edit — high participatory reciprocity.' },
    ],
  },
  {
    externalId: 'e1-gorillaz',
    title: 'Gorillaz (2001)',
    description: 'Damon Albarn and Jamie Hewlett’s virtual band — animated personas standing in for human authorship, a pop precursor to synthetic performers.',
    url: 'https://en.wikipedia.org/wiki/Gorillaz',
    mediaType: 'video',
    publishedAt: '2001-03-26',
    originCountryCodes: ['GB'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.75, reasoning: 'Real creators behind fictional avatars — a deliberately mediated origin.' },
      { axis: 'reach', value: 0.85, reasoning: 'Global chart success across two decades.' },
      { axis: 'aesthetic_signal', value: 0.9, reasoning: 'A singular animated-band visual identity.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'Collaborations span many national scenes.' },
      { axis: 'diplomatic_authenticity', value: 0.65, reasoning: 'Genuine musical craft beneath the avatar conceit.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Extensive cross-cultural collaboration.' },
    ],
  },
  {
    externalId: 'e1-the-sims',
    title: 'The Sims (2000)',
    description: 'The best-selling PC game that turned players into authors of their own media, an early user-generated-content engine.',
    url: 'https://en.wikipedia.org/wiki/The_Sims_(video_game)',
    mediaType: 'mixed',
    publishedAt: '2000-02-04',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear studio origin (Maxis/EA).' },
      { axis: 'reach', value: 0.85, reasoning: 'One of the best-selling franchises in gaming.' },
      { axis: 'aesthetic_signal', value: 0.6, reasoning: 'A recognizable look and invented “Simlish” language.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'Localized and played worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'A culturally neutral sandbox by design.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Vast player-made content ecosystem.' },
    ],
  },
  {
    externalId: 'e1-red-vs-blue',
    title: 'Red vs. Blue (2003)',
    description: 'A comedy series made inside the game Halo — the breakout of machinima, filmmaking democratized through game engines.',
    url: 'https://en.wikipedia.org/wiki/Red_vs._Blue',
    mediaType: 'video',
    publishedAt: '2003-04-01',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.85, reasoning: 'Clearly Rooster Teeth’s authorship.' },
      { axis: 'reach', value: 0.6, reasoning: 'A defining web-video series of its era.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'Established the machinima aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.4, reasoning: 'Largely an Anglophone gaming audience.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'Authentic grassroots-creator provenance.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'Inspired a wave of machinima makers.' },
    ],
  },
  {
    externalId: 'e1-salad-fingers',
    title: 'Salad Fingers (David Firth, 2004)',
    description: 'A surreal Flash animation series emblematic of Newgrounds-era independent web animation.',
    url: 'https://en.wikipedia.org/wiki/Salad_Fingers',
    mediaType: 'video',
    publishedAt: '2004-07-01',
    originCountryCodes: ['GB'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear single-author origin.' },
      { axis: 'reach', value: 0.55, reasoning: 'A widely circulated cult web series.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'A distinctive, unsettling visual style.' },
      { axis: 'diplomatic_cross_boundary', value: 0.45, reasoning: 'Traveled across the Anglophone web.' },
      { axis: 'diplomatic_authenticity', value: 0.7, reasoning: 'Idiosyncratic auteur work.' },
      { axis: 'diplomatic_reciprocity', value: 0.3, reasoning: 'Largely one-way viewing.' },
    ],
  },
  {
    externalId: 'e1-homestar-runner',
    title: 'Homestar Runner / Strong Bad Emails (2000)',
    description: 'A Flash cartoon site whose Strong Bad “emails” answered fan mail — an early creator-audience feedback loop.',
    url: 'https://en.wikipedia.org/wiki/Homestar_Runner',
    mediaType: 'video',
    publishedAt: '2000-12-30',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear two-brother authorship.' },
      { axis: 'reach', value: 0.55, reasoning: 'A defining early-web cartoon following.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'A signature Flash-cartoon style and voice.' },
      { axis: 'diplomatic_cross_boundary', value: 0.35, reasoning: 'Mostly US/Anglophone fandom.' },
      { axis: 'diplomatic_authenticity', value: 0.65, reasoning: 'Authentic independent humor.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Built directly on audience email — reciprocal by format.' },
    ],
  },
  {
    externalId: 'e1-star-wars-kid',
    title: 'Star Wars Kid (2003)',
    description: 'A teenager’s private video, leaked and remixed worldwide — an early, cautionary case of involuntary virality and lost origin control.',
    url: 'https://en.wikipedia.org/wiki/Star_Wars_Kid',
    mediaType: 'video',
    publishedAt: '2003-04-14',
    originCountryCodes: ['CA'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.8, reasoning: 'Origin known, but control over it was lost on release.' },
      { axis: 'reach', value: 0.75, reasoning: 'One of the most-viewed early viral videos.' },
      { axis: 'aesthetic_signal', value: 0.3, reasoning: 'Unstyled home video; remixes added the aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.55, reasoning: 'Globally circulated and remixed.' },
      { axis: 'diplomatic_authenticity', value: 0.5, reasoning: 'Authentic but stripped of consent and context.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'Massively remixed by the crowd.' },
    ],
  },
  {
    externalId: 'e1-numa-numa',
    title: 'Numa Numa (Gary Brolsma, 2004)',
    description: 'A webcam lip-sync to O-Zone’s “Dragostea Din Tei” — one of the first global webcam-performance memes.',
    url: 'https://en.wikipedia.org/wiki/Numa_Numa',
    mediaType: 'video',
    publishedAt: '2004-12-06',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.75, reasoning: 'Known creator performing a Moldovan-Romanian song — layered origin.' },
      { axis: 'reach', value: 0.7, reasoning: 'Among the most-viewed videos of the pre-YouTube web.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'Webcam lo-fi, charm over craft.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'A Eurodance song carried worldwide via an American webcam.' },
      { axis: 'diplomatic_authenticity', value: 0.45, reasoning: 'Joyful appropriation rather than cultural translation.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Launched countless imitation performances.' },
    ],
  },
  {
    externalId: 'e1-dragostea-din-tei',
    title: 'O-Zone, “Dragostea Din Tei” (2003)',
    description: 'A Moldovan-Romanian pop song that became a pan-European hit and the soundtrack to early webcam memes — Global-East-to-West travel.',
    url: 'https://en.wikipedia.org/wiki/Dragostea_Din_Tei',
    mediaType: 'audio',
    publishedAt: '2003-08-01',
    originCountryCodes: ['MD'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clearly attributable Moldovan band O-Zone.' },
      { axis: 'reach', value: 0.8, reasoning: 'Topped charts across Europe and beyond.' },
      { axis: 'aesthetic_signal', value: 0.7, reasoning: 'An indelible Eurodance hook.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'Traveled far from its small-nation origin.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'Authentic origin, though received mostly as catchy sound.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'Spawned global covers and parodies.' },
    ],
  },
  {
    externalId: 'e1-leeroy-jenkins',
    title: 'Leeroy Jenkins (2005)',
    description: 'A World of Warcraft clip that became a defining gaming meme — participatory culture emerging from inside virtual worlds.',
    url: 'https://en.wikipedia.org/wiki/Leeroy_Jenkins',
    mediaType: 'video',
    publishedAt: '2005-05-11',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.65, reasoning: 'Known guild, though staged/authentic debate clouds it.' },
      { axis: 'reach', value: 0.6, reasoning: 'A canonical gaming meme.' },
      { axis: 'aesthetic_signal', value: 0.4, reasoning: 'In-game screen capture aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.4, reasoning: 'Largely within global gaming culture.' },
      { axis: 'diplomatic_authenticity', value: 0.55, reasoning: 'Authentic subcultural humor.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'Endlessly quoted and remixed by players.' },
    ],
  },
  {
    externalId: 'e1-grey-album',
    title: 'Danger Mouse, The Grey Album (2004)',
    description: 'A mashup of Jay-Z’s Black Album and the Beatles’ White Album — a copyright-defying landmark of remix authorship.',
    url: 'https://en.wikipedia.org/wiki/The_Grey_Album',
    mediaType: 'audio',
    publishedAt: '2004-02-01',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.6, reasoning: 'A named producer, but built entirely from others’ origins.' },
      { axis: 'reach', value: 0.65, reasoning: 'Spread through “Grey Tuesday” online protest distribution.' },
      { axis: 'aesthetic_signal', value: 0.8, reasoning: 'A landmark of mashup craft.' },
      { axis: 'diplomatic_cross_boundary', value: 0.5, reasoning: 'Mostly an Anglophone music-culture event.' },
      { axis: 'diplomatic_authenticity', value: 0.7, reasoning: 'Authentic remix artistry foregrounding the question of origin.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Catalyzed a free-culture / remix movement.' },
    ],
  },
  {
    externalId: 'e1-myspace',
    title: 'Myspace (2003)',
    description: 'The social network that let musicians and users self-publish identity and music — a precursor to the creator economy.',
    url: 'https://en.wikipedia.org/wiki/Myspace',
    mediaType: 'text',
    publishedAt: '2003-08-01',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear platform origin.' },
      { axis: 'reach', value: 0.85, reasoning: 'The dominant social network of the mid-2000s.' },
      { axis: 'aesthetic_signal', value: 0.45, reasoning: 'User-customized pages produced a distinctive era aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'Global adoption, especially among musicians.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'A platform layer rather than a cultural work.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'Self-publishing made it broadly participatory.' },
    ],
  },
  {
    externalId: 'e1-second-life',
    title: 'Second Life (2003)',
    description: 'A user-built virtual world where culture, commerce, and even embassies emerged — an early metaverse and digital-diplomacy testbed.',
    url: 'https://en.wikipedia.org/wiki/Second_Life',
    mediaType: 'mixed',
    publishedAt: '2003-06-23',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.7, reasoning: 'Clear platform, but content authored by residents.' },
      { axis: 'reach', value: 0.55, reasoning: 'A landmark virtual world with millions of accounts.' },
      { axis: 'aesthetic_signal', value: 0.5, reasoning: 'A recognizable resident-built aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.7, reasoning: 'Several nations opened virtual embassies inside it.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'Synthetic identities loosen cultural grounding.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'A resident-built, exchange-based economy.' },
    ],
  },
  {
    externalId: 'e1-itunes-store',
    title: 'iTunes Store (2003)',
    description: 'Legal per-track digital downloads that reorganized how recorded culture is bought and circulated.',
    url: 'https://en.wikipedia.org/wiki/ITunes_Store',
    mediaType: 'text',
    publishedAt: '2003-04-28',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear corporate origin (Apple).' },
      { axis: 'reach', value: 0.9, reasoning: 'Became the dominant music retailer of its era.' },
      { axis: 'aesthetic_signal', value: 0.3, reasoning: 'A storefront, not a cultural aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'Restructured global music distribution.' },
      { axis: 'diplomatic_authenticity', value: 0.3, reasoning: 'Neutral distribution infrastructure.' },
      { axis: 'diplomatic_reciprocity', value: 0.2, reasoning: 'A one-way retail channel.' },
    ],
  },
  {
    externalId: 'e1-whassup',
    title: 'Budweiser “Whassup?” (1999)',
    description: 'An ad campaign whose catchphrase became a global, endlessly parodied meme — commercial culture as participatory template.',
    url: 'https://en.wikipedia.org/wiki/Whassup%3F',
    mediaType: 'video',
    publishedAt: '1999-12-20',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear advertiser/agency origin.' },
      { axis: 'reach', value: 0.8, reasoning: 'A globally recognized catchphrase.' },
      { axis: 'aesthetic_signal', value: 0.55, reasoning: 'A simple, hugely imitable format.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'Parodied across many countries.' },
      { axis: 'diplomatic_authenticity', value: 0.35, reasoning: 'Commercial origin, but drawn from a genuine short film.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'Spawned a global wave of parodies.' },
    ],
  },
  {
    externalId: 'e1-counter-strike',
    title: 'Counter-Strike (2000)',
    description: 'A community-made mod that became one of the most-played games ever — user modification as cultural production.',
    url: 'https://en.wikipedia.org/wiki/Counter-Strike',
    mediaType: 'mixed',
    publishedAt: '2000-11-09',
    originCountryCodes: ['US'],
    aiMediation: 'human_made',
    authorshipClass: 'community_collective',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.7, reasoning: 'Began as a fan mod before commercialization.' },
      { axis: 'reach', value: 0.85, reasoning: 'A global, enduring competitive game.' },
      { axis: 'aesthetic_signal', value: 0.5, reasoning: 'Iconic maps and sounds, functional aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'A worldwide competitive community.' },
      { axis: 'diplomatic_authenticity', value: 0.55, reasoning: 'Authentic grassroots-modder origin.' },
      { axis: 'diplomatic_reciprocity', value: 0.6, reasoning: 'A modding-and-tournament participatory culture.' },
    ],
  },
  {
    externalId: 'e1-festen',
    title: 'Festen (The Celebration, 1998)',
    description: 'The first Dogme 95 film — a manifesto-driven turn to stripped-down digital realism in cinema.',
    url: 'https://en.wikipedia.org/wiki/The_Celebration',
    mediaType: 'video',
    publishedAt: '1998-05-19',
    originCountryCodes: ['DK'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear authorship within a named movement.' },
      { axis: 'reach', value: 0.5, reasoning: 'Major festival impact; arthouse reach.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'Defined the Dogme handheld-DV aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'Influenced filmmakers worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.85, reasoning: 'A principled, origin-specific movement.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Inspired international Dogme-certified works.' },
    ],
  },
  {
    externalId: 'e1-spirited-away',
    title: 'Spirited Away (2001)',
    description: 'Miyazaki’s film that won the Academy Award for Animated Feature — Japanese animation traveling to the center of global culture.',
    url: 'https://en.wikipedia.org/wiki/Spirited_Away',
    mediaType: 'video',
    publishedAt: '2001-07-20',
    originCountryCodes: ['JP'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Unmistakable Studio Ghibli / Miyazaki authorship.' },
      { axis: 'reach', value: 0.85, reasoning: 'Global box office and the first non-English animated Oscar.' },
      { axis: 'aesthetic_signal', value: 0.95, reasoning: 'A singular hand-drawn aesthetic.' },
      { axis: 'diplomatic_cross_boundary', value: 0.85, reasoning: 'Carried Japanese folklore worldwide.' },
      { axis: 'diplomatic_authenticity', value: 0.95, reasoning: 'Deeply rooted in Japanese cultural specificity.' },
      { axis: 'diplomatic_reciprocity', value: 0.55, reasoning: 'Helped open Western audiences to anime broadly.' },
    ],
  },
  {
    externalId: 'e1-crouching-tiger',
    title: 'Crouching Tiger, Hidden Dragon (2000)',
    description: 'Ang Lee’s wuxia epic that became the highest-grossing foreign-language film in the US — martial-arts cinema crossing fully into the Western mainstream.',
    url: 'https://en.wikipedia.org/wiki/Crouching_Tiger,_Hidden_Dragon',
    mediaType: 'video',
    publishedAt: '2000-07-06',
    originCountryCodes: ['TW', 'CN'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear authorship; a pan-Chinese co-production.' },
      { axis: 'reach', value: 0.8, reasoning: 'A global crossover hit and multiple-Oscar winner.' },
      { axis: 'aesthetic_signal', value: 0.9, reasoning: 'Iconic wire-fu cinematography.' },
      { axis: 'diplomatic_cross_boundary', value: 0.9, reasoning: 'Wuxia entering the Western mainstream.' },
      { axis: 'diplomatic_authenticity', value: 0.8, reasoning: 'Rooted in the wuxia tradition, packaged for global reach.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'Spurred Western interest in Chinese-language cinema.' },
    ],
  },
  {
    externalId: 'e1-city-of-god',
    title: 'City of God (Cidade de Deus, 2002)',
    description: 'A Brazilian film about Rio’s favelas that achieved global acclaim — Global-South cinema traveling on its own aesthetic force.',
    url: 'https://en.wikipedia.org/wiki/City_of_God_(2002_film)',
    mediaType: 'video',
    publishedAt: '2002-08-30',
    originCountryCodes: ['BR'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear Brazilian authorship and setting.' },
      { axis: 'reach', value: 0.7, reasoning: 'Worldwide critical and arthouse reach; four Oscar nominations.' },
      { axis: 'aesthetic_signal', value: 0.9, reasoning: 'A propulsive, distinctive visual style.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'Brought favela narratives to global audiences.' },
      { axis: 'diplomatic_authenticity', value: 0.9, reasoning: 'Cast and setting rooted in their real communities.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'Raised global interest in Brazilian cinema.' },
    ],
  },
  {
    externalId: 'e1-oldboy',
    title: 'Oldboy (2003)',
    description: 'Park Chan-wook’s film that won the Cannes Grand Prix — a herald of the Korean cinema wave that preceded Hallyu’s global peak.',
    url: 'https://en.wikipedia.org/wiki/Oldboy_(2003_film)',
    mediaType: 'video',
    publishedAt: '2003-11-21',
    originCountryCodes: ['KR'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Unmistakable Park Chan-wook authorship.' },
      { axis: 'reach', value: 0.65, reasoning: 'Global cult and critical reach; a Cannes laureate.' },
      { axis: 'aesthetic_signal', value: 0.9, reasoning: 'A bold, instantly recognizable style.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'A vanguard of Korean cinema’s global rise.' },
      { axis: 'diplomatic_authenticity', value: 0.85, reasoning: 'Strongly rooted in its national cinema.' },
      { axis: 'diplomatic_reciprocity', value: 0.5, reasoning: 'Influenced and was remade by Western filmmakers.' },
    ],
  },
  {
    externalId: 'e1-amelie',
    title: 'Amélie (2001)',
    description: 'Jean-Pierre Jeunet’s film that became a global arthouse phenomenon and a French cultural export.',
    url: 'https://en.wikipedia.org/wiki/Am%C3%A9lie',
    mediaType: 'video',
    publishedAt: '2001-04-25',
    originCountryCodes: ['FR'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear French authorship and setting.' },
      { axis: 'reach', value: 0.75, reasoning: 'One of the highest-grossing French-language films worldwide.' },
      { axis: 'aesthetic_signal', value: 0.9, reasoning: 'A saturated, instantly recognizable look.' },
      { axis: 'diplomatic_cross_boundary', value: 0.8, reasoning: 'A French cultural ambassador abroad.' },
      { axis: 'diplomatic_authenticity', value: 0.8, reasoning: 'A romantic-but-specific portrait of Montmartre.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'Boosted global appetite for French cinema.' },
    ],
  },
  {
    externalId: 'e1-y-tu-mama',
    title: 'Y tu mamá también (2001)',
    description: 'Alfonso Cuarón’s road film that helped launch the global “Three Amigos” wave of Mexican cinema.',
    url: 'https://en.wikipedia.org/wiki/Y_tu_mam%C3%A1_tambi%C3%A9n',
    mediaType: 'video',
    publishedAt: '2001-06-08',
    originCountryCodes: ['MX'],
    aiMediation: 'human_made',
    authorshipClass: 'individual_creator',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear Mexican authorship and setting.' },
      { axis: 'reach', value: 0.65, reasoning: 'A global arthouse breakout.' },
      { axis: 'aesthetic_signal', value: 0.8, reasoning: 'A naturalistic, much-imitated style.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'Carried Mexican cinema into world art houses.' },
      { axis: 'diplomatic_authenticity', value: 0.85, reasoning: 'Grounded in a specific national moment.' },
      { axis: 'diplomatic_reciprocity', value: 0.45, reasoning: 'Launched directors who reshaped global cinema.' },
    ],
  },
  {
    externalId: 'e1-lagaan',
    title: 'Lagaan (2001)',
    description: 'An Indian epic nominated for the Best Foreign Film Oscar — Bollywood reaching for global recognition.',
    url: 'https://en.wikipedia.org/wiki/Lagaan',
    mediaType: 'video',
    publishedAt: '2001-06-15',
    originCountryCodes: ['IN'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Unmistakably Indian production.' },
      { axis: 'reach', value: 0.6, reasoning: 'Wide diaspora reach; an Oscar nominee.' },
      { axis: 'aesthetic_signal', value: 0.8, reasoning: 'Classic Bollywood musical grammar.' },
      { axis: 'diplomatic_cross_boundary', value: 0.65, reasoning: 'Carried Hindi cinema toward Western recognition.' },
      { axis: 'diplomatic_authenticity', value: 0.85, reasoning: 'Rooted in Indian historical and musical tradition.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Built global curiosity about Bollywood.' },
    ],
  },
  {
    externalId: 'e1-final-fantasy-spirits-within',
    title: 'Final Fantasy: The Spirits Within (2001)',
    description: 'The first photorealistic CGI feature with synthetic human actors — an origin point for the synthetic-performer question.',
    url: 'https://en.wikipedia.org/wiki/Final_Fantasy:_The_Spirits_Within',
    mediaType: 'video',
    publishedAt: '2001-07-11',
    originCountryCodes: ['JP'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.9, reasoning: 'Clear studio origin (Square).' },
      { axis: 'reach', value: 0.5, reasoning: 'A famous commercial failure but a technical landmark.' },
      { axis: 'aesthetic_signal', value: 0.85, reasoning: 'Groundbreaking photoreal CGI humans.' },
      { axis: 'diplomatic_cross_boundary', value: 0.6, reasoning: 'A Japanese studio making a Hollywood-style feature.' },
      { axis: 'diplomatic_authenticity', value: 0.4, reasoning: 'Deliberately culturally neutral, near-uncanny realism.' },
      { axis: 'diplomatic_reciprocity', value: 0.3, reasoning: 'A one-way technical demonstration.' },
    ],
  },
  {
    externalId: 'e1-lotr-fellowship',
    title: 'The Lord of the Rings: The Fellowship of the Ring (2001)',
    description: 'Weta’s effects (and the Gollum performance-capture that followed) reset the boundary between human performance and digital character.',
    url: 'https://en.wikipedia.org/wiki/The_Lord_of_the_Rings:_The_Fellowship_of_the_Ring',
    mediaType: 'video',
    publishedAt: '2001-12-19',
    originCountryCodes: ['NZ'],
    aiMediation: 'human_made',
    authorshipClass: 'commercial_institutional',
    era: ERA,
    scores: [
      { axis: 'origin', value: 0.95, reasoning: 'Clear authorship; a New Zealand production.' },
      { axis: 'reach', value: 0.95, reasoning: 'A global blockbuster trilogy.' },
      { axis: 'aesthetic_signal', value: 0.9, reasoning: 'Definitive fantasy visual language and effects.' },
      { axis: 'diplomatic_cross_boundary', value: 0.75, reasoning: 'Worldwide release; put New Zealand on the production map.' },
      { axis: 'diplomatic_authenticity', value: 0.6, reasoning: 'Faithful to its source, a Hollywood-scale adaptation.' },
      { axis: 'diplomatic_reciprocity', value: 0.4, reasoning: 'Mostly one-way export of a global franchise.' },
    ],
  },
];
