/**
 * Fetch Wikipedia page-image thumbnails for seed artifacts whose canonical url is a Wikipedia article
 * and which have no thumbnail yet, and write them to scripts/seed-data/thumbnails.ts (keyed by
 * externalId). The loader merges these in, so a subsequent `npm run seed:corpus` populates them.
 * Polite to Wikimedia (descriptive User-Agent + throttle). Non-fabricated: only real article images.
 *   npm run enrich:thumbnails && npm run seed:corpus
 */
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { sql } from 'drizzle-orm';
import { useScriptDatabaseUrl } from './db-env';

const UA = 'OriginUnknownResearch/1.0 (scholarly corpus; thumbnail fetch) generic-bot';

async function wikiThumb(title: string): Promise<string | null> {
  // Try REST Summary API first (works for most articles with a main image).
  try {
    const sum = `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title)}`;
    const r = await fetch(sum, {
      headers: { 'user-agent': UA, accept: 'application/json' },
      signal: AbortSignal.timeout(8000),
    });
    if (r.ok) {
      const j = (await r.json()) as { thumbnail?: { source?: string } };
      if (j.thumbnail?.source) return j.thumbnail.source;
    }
  } catch { /* fall through */ }

  // Fallback: MediaWiki pageimages action (different image selection logic).
  try {
    const api = `https://en.wikipedia.org/w/api.php?action=query&titles=${encodeURIComponent(title)}&prop=pageimages&format=json&pithumbsize=400`;
    const r2 = await fetch(api, {
      headers: { 'user-agent': UA, accept: 'application/json' },
      signal: AbortSignal.timeout(8000),
    });
    if (r2.ok) {
      const j = (await r2.json()) as {
        query?: { pages?: Record<string, { thumbnail?: { source?: string } }> };
      };
      const page = Object.values(j.query?.pages ?? {})[0];
      if (page?.thumbnail?.source) return page.thumbnail.source;
    }
  } catch { /* no thumbnail available */ }

  return null;
}

async function main() {
  useScriptDatabaseUrl();
  const { db } = await import('../lib/db/client');
  const rows = (await db.execute(sql`
    SELECT a.external_id AS id, a.content_url AS url
    FROM artifacts a JOIN sources s ON s.id = a.source_id
    WHERE s.name = 'Seed Corpus (curated)' AND a.thumbnail_url IS NULL
      AND a.content_url LIKE '%wikipedia.org/wiki/%'
    ORDER BY a.external_id
  `)) as unknown as Array<{ id: string; url: string }>;

  console.log(`Fetching Wikipedia thumbnails for ${rows.length} seed artifacts…`);
  // Load existing so we don't lose previously found thumbnails.
  let existing: Record<string, string> = {};
  try {
    const mod = await import('./seed-data/thumbnails');
    existing = (mod as { THUMBNAILS?: Record<string, string> }).THUMBNAILS ?? {};
  } catch { /* file may not exist yet */ }
  const map: Record<string, string> = { ...existing };
  let ok = 0;
  for (const r of rows) {
    const raw = r.url.split('/wiki/')[1] ?? '';
    const title = decodeURIComponent(raw.split('#')[0]?.split('?')[0] ?? '');
    if (!title) continue;
    const thumb = await wikiThumb(title);
    if (thumb) {
      map[r.id] = thumb;
      ok += 1;
    }
    await new Promise((res) => setTimeout(res, 120));
  }

  const sorted = Object.fromEntries(Object.entries(map).sort(([a], [b]) => a.localeCompare(b)));
  const out = `// Generated by \`npm run enrich:thumbnails\` — Wikipedia REST page-summary thumbnails for seed\n// artifacts whose canonical url is a Wikipedia article. Keyed by externalId. Re-run to refresh.\nexport const THUMBNAILS: Record<string, string> = ${JSON.stringify(sorted, null, 2)};\n`;
  await writeFile(resolve(process.cwd(), 'scripts/seed-data/thumbnails.ts'), out, 'utf8');
  console.log(`Wrote ${ok}/${rows.length} thumbnails to scripts/seed-data/thumbnails.ts`);
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
